/**
 * Mutatii: S20-23, taietura 5 — accesul vertical.
 *
 * Doua panouri de design au demontat primele doua versiuni (22 de CRITIC/MARE, apoi
 * inca 8): siguranta pionului depindea de desemnarile RAMASE, deci memoria decidea si
 * M5 se rupea; colturile etajelor n-aveau loc de lucru; regula de sigilare infometa
 * constructorul. Fiecare garda de aici are testul ei, iar numele probei spune ce apara.
 */

export const MUTATII = [
  // --- pasul 2: continutul ---
  {
    n: 'atingerea poate cobori SUB pas (invariantul pierde capatul de jos)',
    f: 'src/sim/content.ts',
    a: '  if (r.atingereSusM < r.maxStepM || r.atingereSusM > r.agentHeadroomM) {',
    b: '  if (r.atingereSusM > r.agentHeadroomM) {',
    t: 'tests/content.test.ts', e: 'atingerea la zidire: cel putin un pas',
  },
  {
    n: 'atingerea poate trece PESTE cap (invariantul pierde capatul de sus)',
    f: 'src/sim/content.ts',
    a: '  if (r.atingereSusM < r.maxStepM || r.atingereSusM > r.agentHeadroomM) {',
    b: '  if (r.atingereSusM < r.maxStepM) {',
    t: 'tests/content.test.ts', e: 'atingerea la zidire: cel putin un pas',
  },
  {
    n: 'pragul natural al accesului poate trece de plafonul total',
    f: 'src/sim/content.ts',
    a: '  if (r.accesPlafonNatural > r.accesPlafonTotal) {',
    b: '  if (r.accesPlafonNatural > r.accesPlafonTotal + 1000000) {',
    t: 'tests/content.test.ts', e: 'pragul natural al accesului nu poate trece',
  },
  {
    n: 'o piesa poate fi dintr-un material NATURAL',
    f: 'src/sim/content.ts',
    a: '    if (!esteMaterialDeStructura(mat[1])) {',
    b: '    if (!isSolid(mat[1])) {',
    t: 'tests/content.test.ts', e: 'o piesa dintr-un material NATURAL e refuzata',
  },
  {
    n: 'o piesa se poate face din AER (garda de structura scoasa cu totul)',
    f: 'src/sim/content.ts',
    a: '    if (!esteMaterialDeStructura(mat[1])) {',
    b: '    if (false) {',
    t: 'tests/content.test.ts', e: 'o piesa din AER sau APA',
  },
  {
    n: 'orice solid e „de structura" (roca, pamant, moloz numara ca zid)',
    f: 'src/sim/terrain/chunk.ts',
    a: '  return m === Material.PIATRA_CONSTRUITA || m === Material.GRINDA || m === Material.LEMN_CONSTRUIT',
    b: '  return isSolid(m)',
    t: 'tests/content.test.ts', e: 'o piesa dintr-un material NATURAL e refuzata',
  },
  {
    n: 'plafoanele de acces fara plafon de COST',
    f: 'src/sim/content.ts',
    a: '  accesPlafonTotal: { min: 1, max: 16384 },',
    b: '  accesPlafonTotal: { min: 1, max: 1000000 },',
    t: 'tests/content.test.ts', e: 'plafoanele accesului au un plafon de COST',
  },
  {
    n: 'pragul de ridicare nu se mai taie la cantitatea piesei',
    f: 'src/sim/joburi.ts',
    a: '  return Math.min(rules.constructPickupMinUnits, spec.cantitate)',
    b: '  return rules.constructPickupMinUnits',
    t: 'tests/constructie.test.ts', e: 'o piesa de 5 are pragul 5',
  },
  // --- pasul 3: modulul pur ---
  {
    n: 'pragul natural devine strict (o incinta de exact N celule naturale ramane punga)',
    f: 'src/sim/acces.ts',
    a: '        if (naturale >= pragN || celule.length > pragT) deschisa = true',
    b: '        if (naturale > pragN || celule.length > pragT) deschisa = true',
    t: 'tests/acces.test.ts', e: 'pragul NATURAL la granita',
  },
  {
    n: 'plafonul total devine nestrict (un acoperis de exact T celule e declarat deschis)',
    f: 'src/sim/acces.ts',
    a: '        if (naturale >= pragN || celule.length > pragT) deschisa = true',
    b: '        if (naturale >= pragN || celule.length >= pragT) deschisa = true',
    t: 'tests/acces.test.ts', e: 'pragul TOTAL la granita',
  },
  {
    n: 'graful stabil uita santierul din CELULA (se sta pe o piesa planificata)',
    f: 'src/sim/acces.ts',
    a: '      if (C.has(cellKey(x, y, z))) return false\n      if (!isSolid(materialCitit(r, x, y, z - 1))',
    b: '      if (!isSolid(materialCitit(r, x, y, z - 1))',
    t: 'tests/acces.test.ts', e: 'graful STABIL e exact',
  },
  {
    n: 'graful stabil uita santierul din CAP',
    f: 'src/sim/acces.ts',
    a: '        if (isSolid(materialCitit(r, x, y, z + h)) || C.has(cellKey(x, y, z + h))) return false',
    b: '        if (isSolid(materialCitit(r, x, y, z + h))) return false',
    t: 'tests/acces.test.ts', e: 'graful STABIL e exact',
  },
  {
    n: 'graful stabil nu vede podeaua zidita IPOTETIC',
    f: 'src/sim/acces.ts',
    a: '      if (!isSolid(materialCitit(r, x, y, z - 1)) && !ziditaIpotetic(Z, inPlus, cellKey(x, y, z - 1))) return false',
    b: '      if (!isSolid(materialCitit(r, x, y, z - 1))) return false',
    t: 'tests/acces.test.ts', e: 'graful STABIL e exact',
  },
  {
    n: 'podeaua de STRUCTURA numara ca naturala (acoperisul fara scara devine „afara")',
    f: 'src/sim/acces.ts',
    a: '      const m = materialCitit(r, x, y, z - 1)\n      return isSolid(m) && !esteMaterialDeStructura(m)\n    },\n  }\n}\n\n/**\n * Graful lui W',
    b: '      const m = materialCitit(r, x, y, z - 1)\n      return isSolid(m)\n    },\n  }\n}\n\n/**\n * Graful lui W',
    t: 'tests/acces.test.ts', e: 'podeaua NATURALA',
  },
  {
    n: 'coloana nepromovata: pamantul coboara un nivel mai putin',
    f: 'src/sim/acces.ts',
    a: '      mat[l] = z > g ? Material.AER : z === g ? sus : z > g - 3 ? Material.PAMANT : Material.ROCA',
    b: '      mat[l] = z > g ? Material.AER : z === g ? sus : z > g - 2 ? Material.PAMANT : Material.ROCA',
    t: 'tests/acces.test.ts', e: 'citirea pe coloana spune EXACT',
  },
  {
    n: 'afara din lume e AER, nu stanca',
    f: 'src/sim/acces.ts',
    a: '  if (c.afara) return Material.ROCA',
    b: '  if (c.afara) return Material.AER',
    t: 'tests/acces.test.ts', e: 'citirea pe coloana spune EXACT',
  },
  {
    n: 'flood-ul merge doar pe acelasi nivel (pasul de 1 m nu leaga)',
    f: 'src/sim/acces.ts',
    a: '      for (let dz = -pas; dz <= pas && !deschisa; dz++) {',
    b: '      for (let dz = 0; dz <= 0 && !deschisa; dz++) {',
    t: 'tests/acces.test.ts', e: 'siguranta pura',
  },
  {
    n: 'diagonalele INAINTEA ortogonalelor (locul de lucru se muta fara motiv)',
    f: 'src/sim/acces.ts',
    a: 'const DIR8: readonly (readonly [number, number])[] = [...DIR4, [1, 1], [-1, 1], [1, -1], [-1, -1]]',
    b: 'const DIR8: readonly (readonly [number, number])[] = [[1, 1], [-1, 1], [1, -1], [-1, -1], ...DIR4]',
    t: 'tests/acces.test.ts', e: 'nivelurile si vecinatatea',
  },
  {
    n: 'zidirea nu mai ajunge deasupra capului (atingerea = pasul)',
    f: 'src/sim/acces.ts',
    a: '  const jos = fel === FelLucru.CONSTRUIESTE || fel === FelLucru.DECONSTRUIESTE ? Math.max(pas, rules.atingereSusM) : pas',
    b: '  const jos = pas',
    t: 'tests/acces.test.ts', e: 'nivelurile si vecinatatea',
  },
  // --- pasul 4: memoria din lume ---
  {
    n: 'cutia de dependenta nu coboara sub pasul vecinului (marginea din designul v2)',
    f: 'src/sim/acces.ts',
    a: '    z0: c.z0 - pas - 1,',
    b: '    z0: c.z0 - 1,',
    t: 'tests/acces.test.ts', e: 'memoria vede editarea de SUB pasul vecinului',
  },
  {
    n: 'cutia de dependenta nu urca peste capul vecinului de pas (la pas 2)',
    f: 'src/sim/acces.ts',
    a: '    z1: c.z1 + pas + rules.agentHeadroomM - 1,',
    b: '    z1: c.z1 + rules.agentHeadroomM,',
    t: 'tests/acces.test.ts', e: 'memoria vede editarea de PESTE capul vecinului',
  },
  {
    n: 'cutia de dependenta fara vecinii din stanga',
    f: 'src/sim/acces.ts',
    a: '    x0: c.x0 - 1,',
    b: '    x0: c.x0,',
    t: 'tests/acces.test.ts', e: 'memoria vede editarile de pe marginea ORIZONTALA',
  },
  {
    n: 'cutia de dependenta fara vecinii de sus (y)',
    f: 'src/sim/acces.ts',
    a: '    y1: c.y1 + 1,',
    b: '    y1: c.y1,',
    t: 'tests/acces.test.ts', e: 'memoria vede editarile de pe marginea ORIZONTALA',
  },
  {
    n: 'stergerea unui santier nu intra in jurnal',
    f: 'src/sim/desemnari.ts',
    a: '    d.viiConstruieste--\n    noteazaConstr(d, slot)',
    b: '    d.viiConstruieste--',
    t: 'tests/acces.test.ts', e: 'memoria accesului == recalculul de la zero',
  },
  {
    n: 'jurnalul terenului scrie alta coloana decat cea editata',
    f: 'src/sim/terrain/terrain.ts',
    a: '  t.jurnal[j] = wx',
    b: '  t.jurnal[j] = wx + 1000',
    t: 'tests/acces.test.ts', e: 'memoria vede editarile de pe marginea ORIZONTALA',
  },
  {
    n: 'depasirea jurnalului nu mai goleste memoria',
    f: 'src/sim/acces.ts',
    a: '  if (nd > JURNAL_DESEMNARI_CAP || nt > JURNAL_CAP) {',
    b: '  if (nd > JURNAL_DESEMNARI_CAP * 1000 || nt > JURNAL_CAP * 1000) {',
    t: 'tests/acces.test.ts', e: 'memoria accesului == recalculul de la zero',
  },
  {
    n: 'planul din memorie nu pierde santierele zidite sau anulate',
    f: 'src/sim/acces.ts',
    a: '      if (m.plan.delete(k)) scoase.add(k)',
    b: '      if (m.plan.has(k)) scoase.add(k)',
    t: 'tests/acces.test.ts', e: 'memoria accesului == recalculul de la zero',
  },
  {
    n: 'orice editare din lume goleste toate flood-urile (R3)',
    f: 'src/sim/acces.ts',
    a: '    if (x < f.x0 || x > f.x1 || y < f.y0 || y > f.y1 || z < f.z0 || z > f.z1) continue',
    b: '    if (x === f.x0 && x === -1) continue',
    t: 'tests/acces.test.ts', e: 'memoria accesului == recalculul de la zero',
  },
  {
    n: 'cititorul de coloane nu se reimprospateaza dupa o editare',
    f: 'src/sim/acces.ts',
    a: '  if (m.cititor === null || m.cititorLa !== t.editari) {',
    b: '  if (m.cititor === null) {',
    t: 'tests/acces.test.ts', e: 'memoria accesului == recalculul de la zero',
  },
  // --- pasul 5: D1 + D2 in joc ---
  {
    n: 'locul de lucru la zidire nu mai trebuie sa fie SIGUR (pionul urca pe creasta)',
    f: 'src/sim/joburi.ts',
    a: '      if (sigura !== null && !sigura(nx, ny, zs)) continue',
    b: '      void sigura',
    t: 'tests/acces-joc.test.ts', e: 'ACCEPTANTA: camera fara usa',
  },
  {
    n: 'fara privirea inainte (pionul prins nu-si zideste iesirea)',
    f: 'src/sim/joburi.ts',
    a: '    siguraMemorat(w.terrain, w.desemnari, rules, w.acces, x, y, z) ||\n    siguraDupaZidire(w.terrain, w.desemnari, rules, w.acces, x, y, z, px, py, pz)',
    b: '    siguraMemorat(w.terrain, w.desemnari, rules, w.acces, x, y, z)',
    t: 'tests/acces-joc.test.ts', e: 'PRIVIREA INAINTE',
  },
  {
    n: 'sigilarea nu se verifica la PRIMUL tick de munca (se munceste pe o piesa refuzata)',
    f: 'src/sim/joburi.ts',
    a: '  if (a.jobProgres[slot] === 0) {\n    const inchide = arInchideCeva(w, rules, d.wx[ds]!, d.wy[ds]!, d.z[ds]!)',
    b: '  if (a.jobProgres[slot] === -1) {\n    const inchide = arInchideCeva(w, rules, d.wx[ds]!, d.wy[ds]!, d.z[ds]!)',
    t: 'tests/acces-joc.test.ts', e: 'SIGILAREA la primul tick',
  },
  {
    n: 'sigilarea nu se verifica INAINTE de zidire (cine a intrat intre timp e zidit)',
    f: 'src/sim/joburi.ts',
    a: '  // Si inainte de zidire: in cele `lucru` tickuri cineva poate intra in incinta.\n  const inchide = arInchideCeva(w, rules, d.wx[ds]!, d.wy[ds]!, d.z[ds]!)\n  if (!inchide.ok) {',
    b: '  // Si inainte de zidire: in cele `lucru` tickuri cineva poate intra in incinta.\n  const inchide = arInchideCeva(w, rules, d.wx[ds]!, d.wy[ds]!, d.z[ds]!)\n  if (inchide.ok === 7 as unknown) {',
    t: 'tests/acces-joc.test.ts', e: 'SIGILAREA la zidire',
  },
  {
    n: 'locul de lucru nu se revalideaza in timpul muncii',
    f: 'src/sim/joburi.ts',
    a: '  if (!peLoc || seSapaLa(d, cx, cy, cz - 1) || !locSigurPentru(w, rules, d.wx[ds]!, d.wy[ds]!, d.z[ds]!)(cx, cy, cz)) {',
    b: '  if (!peLoc || seSapaLa(d, cx, cy, cz - 1)) {',
    t: 'tests/acces-joc.test.ts', e: 'REVALIDAREA',
  },
  {
    n: 'la oprire, cauza e mereu „niciun loc de lucru" (minte cand locul e doar nesigur)',
    f: 'src/sim/joburi.ts',
    a: '  return oricare ? DetaliuMotiv.FARA_LOC_SIGUR : DetaliuMotiv.FARA_LOC_DE_LUCRU',
    b: '  return oricare ? DetaliuMotiv.FARA_LOC_DE_LUCRU : DetaliuMotiv.FARA_LOC_DE_LUCRU',
    t: 'tests/acces-joc.test.ts', e: 'REVALIDAREA',
  },
  {
    n: 'scanerul nu deosebeste „niciun loc SIGUR" de „niciun loc"',
    f: 'src/sim/joburi.ts',
    a: '          d.ultimulMotivDetaliu[s] = nesigur ? DetaliuMotiv.FARA_LOC_SIGUR : DetaliuMotiv.FARA_LOC_DE_LUCRU',
    b: '          d.ultimulMotivDetaliu[s] = nesigur ? DetaliuMotiv.FARA_LOC_DE_LUCRU : DetaliuMotiv.FARA_LOC_DE_LUCRU',
    t: 'tests/acces-joc.test.ts', e: 'ACCEPTANTA: fara scara, etajul si acoperisul',
  },
  {
    n: 'sigilarea refuza si ce era DEJA inchis (gardul din jurul gropii nu se mai ridica)',
    f: 'src/sim/acces.ts',
    a: '      if (deschisaInW) {\n        puse[id] = true\n        out.push(cuP_[id]!)\n      }',
    b: '      if (true) {\n        puse[id] = true\n        out.push(cuP_[id]!)\n      }',
    t: 'tests/acces-joc.test.ts', e: 'SIGILAREA inchide doar ce era DESCHIS',
  },
  {
    n: 'sigilarea nu vede PIONII inchisi',
    f: 'src/sim/joburi.ts',
    a: '      const pion = pioni.get(k)\n      if (pion !== undefined) {',
    b: '      const pion = pioni.get(k)\n      if (pion === -12345) {',
    t: 'tests/acces-joc.test.ts', e: 'SIGILAREA la zidire',
  },
  {
    n: 'sigilarea nu vede MORMANELE inchise',
    f: 'src/sim/joburi.ts',
    a: '      if (it !== -1) return refuse(Reason.AR_INCHIDE,',
    b: '      if (it === -12345) return refuse(Reason.AR_INCHIDE,',
    t: 'tests/acces-joc.test.ts', e: 'SIGILAREA: un morman sau o celula de depozit',
  },
  {
    n: 'sigilarea nu vede celulele de DEPOZIT inchise',
    f: 'src/sim/joburi.ts',
    a: '      if (celulaDeZonaLa(w.zone, c.wx, c.wy, c.z) !== -1) return refuse(Reason.AR_INCHIDE,',
    b: '      if (celulaDeZonaLa(w.zone, c.wx, c.wy, c.z) === -12345) return refuse(Reason.AR_INCHIDE,',
    t: 'tests/acces-joc.test.ts', e: 'SIGILAREA: un morman sau o celula de depozit',
  },
  {
    n: 'zidirea fara diagonala (colturile etajului raman)',
    f: 'src/sim/acces.ts',
    a: '  return fel === FelLucru.CONSTRUIESTE || fel === FelLucru.DECONSTRUIESTE ? DIR8 : DIR4',
    b: '  return DIR4',
    t: 'tests/acces-joc.test.ts', e: 'ACCEPTANTA: casa cu doua etaje si scara interioara se ridica INTEGRAL',
  },
  // --- pasul 6: previzualizarea ---
  {
    n: 'inchiderea previzualizarii ignora accesul (promite ce pionii nu zidesc)',
    f: 'src/sim/stabilitate.ts',
    a: '      if (acces !== null && !acces.poate(cheie, zidite)) continue',
    b: '      void acces',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA: fara scara',
  },
  {
    n: 'previzualizarea fara privirea inainte (salvarea din groapa nu e promisa)',
    f: 'src/sim/acces.ts',
    a: '      for (const i of inchise) if (vecine.has(i) && areConstructor(e, i)) return true',
    b: '      void vecine',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA promite si salvarea',
  },
  {
    n: 'cauza nu se uita la podeaua pungii (placa fara scara iese INCINTA)',
    f: 'src/sim/acces.ts',
    a: '      if (!e.deschisa[id] && e.naturale[id]! > 0) return CauzaAcces.INCINTA',
    b: '      if (!e.deschisa[id] && e.naturale[id]! >= 0) return CauzaAcces.INCINTA',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA: fara scara',
  },
  {
    n: 'pungile planului numara si ce era DEJA inchis',
    f: 'src/sim/acces.ts',
    a: '          if (!comp.deschisa) continue\n        }\n        out.push(k)',
    b: '        }\n        out.push(k)',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA numara ce ar INCHIDE',
  },
  // --- pasul 8: costul ---
  {
    n: 'previzualizarea reface etichetarea la FIECARE piesa (costul prim, 3,4 s)',
    f: 'src/sim/acces.ts',
    a: '      if (et === null || lumeaEt !== zidite) {',
    b: '      if (true) {',
    t: 'tests/acces-joc.test.ts', e: 'K05: previzualizarea inunda',
  },
  {
    n: 'memoria scanerului nu retine etichetele (fiecare intrebare inunda)',
    f: 'src/sim/acces.ts',
    a: '  for (const v of c.celule) eticheteaza(m, v, idx)',
    b: '  for (const v of c.celule) void v',
    t: 'tests/acces-joc.test.ts', e: 'K05: accesul din simulare',
  },
  // --- recenzia din 27.09: regula de sigilare ---
  {
    n: 'sigilarea: PRIMA samanta a componentei decide (forma veche; pionul zidit in camera cu podea inaltata)',
    f: 'src/sim/acces.ts',
    a: '      if (deschisaInW) {\n        puse[id] = true\n        out.push(cuP_[id]!)\n      }',
    b: '      puse[id] = true\n      if (deschisaInW) {\n        out.push(cuP_[id]!)\n      }',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA [ordine]: p inchide interiorul',
  },
  {
    n: 'semintele sigilarii nu coboara sub pz − 1 (buiandrugul camerei adancite)',
    f: 'src/sim/acces.ts',
    a: '    for (let z = pz - H - pas; z <= pz + 1 + pas; z++) {\n      if (!cuP.calcabila(x, y, z)) continue',
    b: '    for (let z = pz - 1; z <= pz + 1 + pas; z++) {\n      if (!cuP.calcabila(x, y, z)) continue',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA [adancita]: p inchide interiorul',
  },
  {
    n: 'semintele sigilarii nu urca peste pz (pragul camerei inaltate)',
    f: 'src/sim/acces.ts',
    a: '    for (let z = pz - H - pas; z <= pz + 1 + pas; z++) {\n      if (!cuP.calcabila(x, y, z)) continue',
    b: '    for (let z = pz - H - pas; z <= pz; z++) {\n      if (!cuP.calcabila(x, y, z)) continue',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA [inaltata]: p inchide interiorul',
  },
  {
    n: 'saltul sigilarii se uita doar la celula piesei (buiandrugul nu mai inchide nimic)',
    f: 'src/sim/acces.ts',
    a: '  for (let h = 0; h < H && !scoate; h++) if (faraP.calcabila(px, py, pz - h)) scoate = true',
    b: '  for (let h = 0; h < 1 && !scoate; h++) if (faraP.calcabila(px, py, pz - h)) scoate = true',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA [adancita]: p inchide interiorul',
  },
  {
    n: 'sigilarea nu mai sare piesele care nu scot nimic (doua flood-uri pe fiecare placa)',
    f: 'src/sim/acces.ts',
    a: '  let scoate = false\n',
    b: '  let scoate = true\n',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA sare piesa',
  },
  {
    n: 'sigilarea pe memorie se opreste si la etichetele INCHISE (o punga trece drept deschisa)',
    f: 'src/sim/acces.ts',
    a: '    return e !== undefined && m.floods[e]!.deschisa\n  }\n  return componenteInchiseDe(',
    b: '    return e !== undefined\n  }\n  return componenteInchiseDe(',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA pe memorie == forma pura',
  },
  {
    n: 'sigilarea nu se mai opreste la etichetele deschise ale memoriei (costul: ~1,2 M celule pe casa)',
    f: 'src/sim/acces.ts',
    a: '        if (dovedita !== null && dovedita(k)) deschisa = true\n',
    b: '',
    t: 'tests/acces-joc.test.ts', e: 'K05: accesul din simulare',
  },
  {
    n: 'raspunsul „deschisa in W" retinut pe componenta marcheaza deschise si pungile',
    f: 'src/sim/acces.ts',
    a: '        for (const c of acum.celule) inW.set(c, acum.deschisa)',
    b: '        for (const c of acum.celule) inW.set(c, true)',
    t: 'tests/acces-sigilare.test.ts', e: 'SIGILAREA: o piesa pe fundul unei gropi deja inchise',
  },
  // --- recenzia din 27.09: memoria ---
  {
    n: 'orice editare de teren e tratata monoton (memoria tine deschis ce s-a inchis)',
    f: 'src/sim/acces.ts',
    a: '    let monotona = (m.plan.has(k) || scoase.has(k)) && ori.get(k) === 1',
    b: '    let monotona = true',
    t: 'tests/acces.test.ts', e: 'memoria == recalculul pe FERESTRE',
  },
  {
    n: 'monotonia fara „o singura intrare pe celula" (molozul de pe santier sapat si zidit)',
    f: 'src/sim/acces.ts',
    a: ' && ori.get(k) === 1',
    b: '',
    t: 'tests/acces.test.ts', e: 'memoria pe molozul unui santier',
  },
  {
    n: 'monotonia fara „solida acum" (molozul sapat de pe santier tine flood-ul deschis)',
    f: 'src/sim/acces.ts',
    a: '      monotona = mt.ok && isSolid(mt.value)',
    b: '      monotona = mt.ok',
    t: 'tests/acces.test.ts', e: 'memoria == recalculul pe FERESTRE',
  },
  {
    n: 'un santier NOU e tratat ca editare monotona (F se strange, memoria nu vede)',
    f: 'src/sim/acces.ts',
    a: '      m.plan.add(k)\n      invalideaza(m, x, y, z, false)',
    b: '      m.plan.add(k)\n      invalideaza(m, x, y, z, true)',
    t: 'tests/acces-joc.test.ts', e: 'REVALIDAREA',
  },
  {
    n: 'editarea monotona sterge si flood-urile deschise (o reinundare „afara" la fiecare zidire)',
    f: 'src/sim/acces.ts',
    a: '    if (monotona && f.deschisa) continue',
    b: '    if (monotona && f.deschisa && false) continue',
    t: 'tests/acces-joc.test.ts', e: 'K05: accesul din simulare',
  },
  {
    n: 'flood-ul ramas fara etichete nu se elibereaza',
    f: 'src/sim/acces.ts',
    a: '    if (--f.etichete === 0) {',
    b: '    if (--f.etichete === -1) {',
    t: 'tests/acces.test.ts', e: 'memoria elibereaza',
  },
  {
    n: 'golirea memoriei pastreaza cititorul terenului vechi',
    f: 'src/sim/acces.ts',
    a: '  m.cititor = null\n  m.cititorLa = -1\n}',
    b: '}',
    t: 'tests/acces.test.ts', e: 'memoria refolosita pe ALT teren',
  },
  // --- recenzia din 27.09: privirea inainte pe memorie ---
  {
    n: 'privirea pe memorie nu cere ca punga celulei de lucru sa atinga celula noua',
    f: 'src/sim/acces.ts',
    a: '  if (!gasita) return false',
    b: '  void gasita',
    t: 'tests/acces.test.ts', e: 'memoria == recalculul pe FERESTRE',
  },
  {
    n: 'privirea pe memorie nu cere celula de peste p calcabila',
    f: 'src/sim/acces.ts',
    a: '  const sus = nodStabil({ t, plan: m.plan, zidite: null, inPlus: cellKey(px, py, pz) }, rules, r)\n  if (!sus.calcabila(px, py, pz + 1)) return false',
    b: '  const sus = nodStabil({ t, plan: m.plan, zidite: null, inPlus: cellKey(px, py, pz) }, rules, r)\n  void sus',
    t: 'tests/acces.test.ts', e: 'memoria == recalculul pe FERESTRE',
  },
  {
    n: 'privirea pe memorie numara de doua ori aceeasi punga vecina',
    f: 'src/sim/acces.ts',
    a: '      if (vecine.includes(id)) continue',
    b: '      void 0',
    t: 'tests/acces.test.ts', e: 'memoria == recalculul pe FERESTRE',
  },
  {
    n: 'privirea pe memorie: pragul natural strict',
    f: 'src/sim/acces.ts',
    a: '  return deschisa || naturale >= rules.accesPlafonNatural || total > rules.accesPlafonTotal',
    b: '  return deschisa || naturale > rules.accesPlafonNatural || total > rules.accesPlafonTotal',
    t: 'tests/acces.test.ts', e: 'privirea pe memorie la GRANITA',
  },
  {
    n: 'privirea pe memorie: plafonul total nestrict',
    f: 'src/sim/acces.ts',
    a: '  return deschisa || naturale >= rules.accesPlafonNatural || total > rules.accesPlafonTotal',
    b: '  return deschisa || naturale >= rules.accesPlafonNatural || total >= rules.accesPlafonTotal',
    t: 'tests/acces.test.ts', e: 'privirea pe memorie la GRANITA',
  },
  // --- recenzia din 27.09: previzualizarea ---
  {
    n: 'privirea inainte a previzualizarii aduna si pungile etichetate pe un Z mai mic (masa: promisa intr-o ordine)',
    f: 'src/sim/acces.ts',
    a: '      if (!deschisa && veche) return false\n',
    b: '',
    t: 'tests/acces-joc.test.ts', e: 'INCHIDEREA SIMULATA nu depinde de ordinea planului: masa naturala',
  },
  {
    n: 'epoca unei componente se rescrie la fiecare intrebare (garda nu mai vede nimic vechi)',
    f: 'src/sim/acces.ts',
    a: '    if (epoca[i] === undefined) epoca[i] = Z.size',
    b: '    epoca[i] = Z.size',
    t: 'tests/acces-joc.test.ts', e: 'INCHIDEREA SIMULATA nu depinde de ordinea planului: masa naturala',
  },
  {
    n: 'privirea inainte a previzualizarii nu cere un constructor in punga (groapa goala promisa)',
    f: 'src/sim/acces.ts',
    a: '    for (const k of constructori) if (e.comp.get(k) === i) return true\n    return false',
    b: '    return true',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA nu promite privirea inainte dintr-o groapa fara niciun constructor',
  },
  {
    n: 'orice pion viu e constructor pentru previzualizare (si salbaticul)',
    f: 'src/sim/joburi.ts',
    a: '    if (a.faction[i] === Faction.ASEZARE) constructori.push(k)',
    b: '    constructori.push(k)',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA nu promite privirea inainte dintr-o groapa fara niciun constructor',
  },
  {
    n: 'si pungile inchise intra in celulele dovedite deschise ale previzualizarii',
    f: 'src/sim/acces.ts',
    a: '  if (D !== null && c.deschisa) for (const v of c.celule) D.add(v)',
    b: '  if (D !== null) for (const v of c.celule) D.add(v)',
    t: 'tests/acces-joc.test.ts', e: 'PREVIZUALIZAREA: fara scara',
  },
  {
    n: 'previzualizarea nu se mai opreste la celulele dovedite deschise (fiecare celula noua redovedeste „afara")',
    f: 'src/sim/acces.ts',
    a: '  const c = componenta(e.nod, rules, x, y, z, D === null ? null : (v) => D.has(v))',
    b: '  const c = componenta(e.nod, rules, x, y, z)',
    t: 'tests/acces-joc.test.ts', e: 'K05: previzualizarea casei cu scara',
  },
  {
    n: 'pungile planului numara si componentele DESCHISE la capat',
    f: 'src/sim/acces.ts',
    a: '          for (const v of comp.celule) (comp.deschisa ? deschise : out).add(v)',
    b: '          for (const v of comp.celule) out.add(v)',
    t: 'tests/acces-joc.test.ts', e: 'PUNGILE PLANULUI',
  },
  {
    n: 'semintele pungilor planului nu coboara sub piesa',
    f: 'src/sim/acces.ts',
    a: '        for (let z = pz - H - pas; z <= pz + 1 + pas; z++) {\n          if (!dupa.calcabila(x, y, z) || vazute.has(cellKey(x, y, z))) continue',
    b: '        for (let z = pz; z <= pz + 1 + pas; z++) {\n          if (!dupa.calcabila(x, y, z) || vazute.has(cellKey(x, y, z))) continue',
    t: 'tests/acces-joc.test.ts', e: 'PUNGILE PLANULUI',
  },
]
