/**
 * Mutatii: Taietura 2: iteme, carat, zone pictate.
 *
 * 46 de probe. Fiecare intrare: `n` numele, `f` fisierul, `a` tiparul cautat,
 * `b` cu ce se inlocuieste, `t` fisierul de teste care trebuie sa se inroseasca,
 * `e` inceputul numelui testului care trebuie sa pice. `e2` adauga editari.
 *
 * Tiparele se ancoreaza pe o linie UNICA, si de preferat una din CORPUL unei
 * functii, nu doar pe antetul ei: un tipar care se potriveste in doua locuri
 * otraveste primul, adica alta garda decat cea vizata, si „trece" fiindca strica
 * altceva. S-a intamplat.
 */

export const MUTATII = [
  { n: 'cereriPentru citeste cantitatea VIE, nu jobCantitate', f: 'src/sim/joburi.ts',
    a: "    return cereriCara(rules, a.jobTarget[slot]!, a.jobDest[slot]!, a.jobCantitate[slot]!, a.jobStep[slot]!)",
    b: "    const is = slotItem(w.iteme, a.jobTarget[slot]!)\n    return cereriCara(rules, a.jobTarget[slot]!, a.jobDest[slot]!, is === -1 ? a.jobCantitate[slot]! : Math.min(w.iteme.cantitate[is]!, rules.haulCarryMax), a.jobStep[slot]!)",
    t: 'tests/carat.test.ts', e: 'M5 in cei PATRU pasi' },
  { n: 'sursa se cere si dupa RIDICA (fara pas in cereri)', f: 'src/sim/joburi.ts',
    a: "  if (step <= PasCara.RIDICA) cereri.push(", b: "  if (step <= PasCara.LASA) cereri.push(",
    t: 'tests/carat.test.ts', e: 'M5 in cei PATRU pasi' },
  { n: 'RIDICA elibereaza toata perechea, nu doar sursa', f: 'src/sim/joburi.ts',
    a: "  elibereazaUna(w.rezervari, a.id[slot]!, a.jobId[slot]!, idItem, Strat.CARAT)", b: "  elibereaza(w.rezervari, a.id[slot]!, a.jobId[slot]!)",
    t: 'tests/carat.test.ts', e: 'M5 in cei PATRU pasi' },
  { n: 'marfa NU se lasa la picioare la sfarsit de job', f: 'src/sim/joburi.ts',
    a: "  const rezultat = lasaLaPicioare(w, rules, slot)\n", b: "  const rezultat = -1\n  a.caraKind[slot] = 0\n  a.caraCantitate[slot] = 0\n",
    t: 'tests/carat.test.ts', e: 'kill in MERGE_DEST' },
  { n: 'asazaItem nu sare peste celulele rezervate ca destinatie', f: 'src/sim/iteme.ts',
    a: "          if (rezervataCaDestinatie(w, nx, ny, zs)) continue\n", b: "",
    t: 'tests/carat.test.ts', e: 'o celula rezervata ca destinatie' },
  { n: 'carligul podelei scos: mormanul ramane in aer', f: 'src/sim/joburi.ts',
    a: "  if (sus !== -1) mutaItem(w, rules, sus, wx, wy, z)\n", b: "",
    t: 'tests/iteme.test.ts', e: 'podeaua sapata de sub un morman' },
  // Tiparul include si prima liniedin corp: de cand garda pentru PIONI are si ea
  // o bucla pe headroom, un tipar doar pe antet potrivea prima aparitie si
  // otravea garda gresita — mutatia „trecea" fiindca strica altceva.
  { n: 'fill nu se uita la mormane', f: 'src/sim/commands.ts',
    a: "  for (let h = 0; h < rules.agentHeadroomM; h++) {\n    const it = itemLaCelula(w.iteme, wx, wy, z - h)",
    b: "  for (let h = 0; h < 0; h++) {\n    const it = itemLaCelula(w.iteme, wx, wy, z - h)",
    t: 'tests/iteme.test.ts', e: 'fill refuza sa zideasca peste un morman' },
  { n: 'sapatul nu verifica plafonul de iteme', f: 'src/sim/joburi.ts',
    a: "  if (w.iteme.vii >= w.iteme.capacity) {", b: "  if (w.iteme.vii < 0) {",
    t: 'tests/iteme.test.ts', e: 'plafonul de iteme' },
  { n: 'pierderea nu se numara', f: 'src/sim/iteme.ts',
    a: "  if (ramas > 0) w.ratiune.itemePierdute += ramas\n", b: "",
    t: 'tests/iteme.test.ts', e: 'asazaItem: cand NICIO celula' },
  { n: 'pictarea nu intinde acoperirea (discul scos)', f: 'src/sim/commands.ts',
    a: "          acoperaDesemnarea(w, rules, x, y, cmd.z)\n", b: "",
    t: 'tests/carat.test.ts', e: 'depozit la 5 blocuri' },
  // Starea de dinaintea reparatiei K05: coridorul pion → marfa, intins la fiecare
  // evaluare. Acoperirea creste nemarginit; garda noua trebuie sa pice.
  { n: 'coridor pion -> marfa restaurat (K05)', f: 'src/sim/joburi.ts',
    a: "    const r = regionAt(w.regions, ixx, iy, iz)", b: "    let r = regionAt(w.regions, ixx, iy, iz)",
    e2: [{ f: 'src/sim/joburi.ts',
      a: "    if (r === NO_REGION || find(w.regions, r) !== compAgent) {\n      raport.inaccesibil++\n      memoreazaPeItem(w, rules, s, Reason.INACCESIBIL, DetaliuItem.COMPONENTE_DIFERITE)\n      noteaza(Reason.INACCESIBIL)\n      continue\n    }",
      b: "    if (r === NO_REGION || find(w.regions, r) !== compAgent) {\n      if (acoperaCoridor(w, rules, ax, ay, az, ixx, iy, iz)) {\n        compAgent = find(w.regions, regionAt(w.regions, ax, ay, az))\n        r = regionAt(w.regions, ixx, iy, iz)\n      }\n      if (r === NO_REGION || find(w.regions, r) !== compAgent) {\n        raport.inaccesibil++\n        memoreazaPeItem(w, rules, s, Reason.INACCESIBIL, DetaliuItem.COMPONENTE_DIFERITE)\n        noteaza(Reason.INACCESIBIL)\n        continue\n      }\n    }" }],
    t: 'tests/carat.test.ts', e: 'K05: un morman pe veci inaccesibil' },
  // --- gardele de dupa recenzia codului ---
  { n: 'INACCESIBIL nu numara o incercare', f: 'src/sim/joburi.ts',
    a: "  a.jobIncercari[slot] = a.jobIncercari[slot]! + 1\n  if (a.jobIncercari[slot]! >= rules.jobMaxIncercari) {",
    b: "  if (motiv !== Reason.INACCESIBIL) a.jobIncercari[slot] = a.jobIncercari[slot]! + 1\n  if (a.jobIncercari[slot]! >= rules.jobMaxIncercari) {",
    t: 'tests/joburi.test.ts', e: 'INACCESIBIL numara o incercare' },
  { n: 're-alegerea nu sare peste tinta curenta', f: 'src/sim/joburi.ts',
    // Re-ancorata: codul s-a mutat in `DRIVER_SAPA.refaTinta` (tabelul de drivere).
    a: "    return refaLoculDeLucru(w, rules, slot, cellKey(a.jobWorkX[slot]!, a.jobWorkY[slot]!, a.jobWorkZ[slot]!))",
    b: "    void cellKey\n    return refaLoculDeLucru(w, rules, slot)",
    // Prinsa de testul cu ostilul, nu de cel de INACCESIBIL: contorul singur
    // asigura terminarea, iar `evita` e o proprietate separata („refacut inseamna
    // ALTA celula"), pe care testul ostilului o probeaza de la taietura 1.
    t: 'tests/joburi.test.ts', e: 'un ostil care STA pe prima celula de lucru' },
  { n: 'incarcarea lasa marfa la picioare in aceeasi trecere', f: 'src/sim/joburi.ts',
    a: "    deGolit.push(i)\n    anulate++", b: "    if (a.alive[i] === 1) lasaLaPicioare(w, rules, i)\n    else { a.caraKind[i] = 0; a.caraCantitate[i] = 0 }\n    anulate++",
    t: 'tests/carat.test.ts', e: 'la incarcare, marfa se lasa la picioare DUPA' },
  { n: 'marfa unui slot mort nu se numara', f: 'src/sim/joburi.ts',
    a: "      w.ratiune.itemePierdute += a.caraCantitate[i]!\n", b: "",
    t: 'tests/carat.test.ts', e: 'marfa din mana unui slot MORT' },
  { n: 'fill verifica doar cota picioarelor pionului', f: 'src/sim/commands.ts',
    a: "  for (let h = 0; h < rules.agentHeadroomM; h++) {\n    for (let i = 0; i < a.count; i++) {\n      if (a.alive[i] === 0) continue\n      if (a.z[i] !== z - h) continue",
    b: "  for (let h = 0; h < 1; h++) {\n    for (let i = 0; i < a.count; i++) {\n      if (a.alive[i] === 0) continue\n      if (a.z[i] !== z - h) continue",
    t: 'tests/carat.test.ts', e: 'fill nu zideste un pion la inaltimea capului' },
  { n: 'pionul ingropat isi pastreaza jobul', f: 'src/sim/agents.ts',
    a: "        terminaJob(w, rules, i, Sfarsit.INTRERUPT)\n        continue", b: "        continue",
    t: 'tests/carat.test.ts', e: 'un pion ingropat din care nu se mai iese' },
  { n: 'racirea de pereche ajunge pe item (conditia veche)', f: 'src/sim/joburi.ts',
    a: "  if (evitate > 0) return refuse(Reason.FARA_DEPOZIT, { detaliu: 'evitate', zone: zoneCuLoc, evitate })",
    b: "  if (zoneCuLoc > 0 && evitate === zoneCuLoc) return refuse(Reason.FARA_DEPOZIT, { detaliu: 'evitate', zone: zoneCuLoc, evitate })",
    t: 'tests/carat.test.ts', e: 'o zona EVITATA de un pion' },
  { n: 'marfa se evapora la depunere (-1 unitate)', f: 'src/sim/joburi.ts',
    a: "    w.iteme.cantitate[it] = w.iteme.cantitate[it]! + cant", b: "    w.iteme.cantitate[it] = w.iteme.cantitate[it]! + cant - 1",
    t: 'tests/carat.test.ts', e: 'ACCEPTANTA' },
  // --- tranșa de cost K05 ---
  { n: 'poarta ieftina intreaba „e loc?" in loc de „incape cat car?"', f: 'src/sim/joburi.ts',
    a: "    if (ix.maxLocLiber[zs * ITEME + kind]! < cant) continue", b: "    if (ix.acceptante[zs * ITEME + kind] === 0) continue",
    e2: [{ f: 'src/sim/zone.ts', a: "    if (ix.maxPrioLibera[it.kind[i]!]! > prioLoc && incapeUndeva(s, ix, it.kind[i]!, cant, prioLoc)) {", b: "    if (ix.maxPrioLibera[it.kind[i]!]! > prioLoc) {" }],
    t: 'tests/carat.test.ts', e: 'poarta ieftina intreaba' },
  { n: 'plafonul de destinatie numara potriviri, nu intrari', f: 'src/sim/joburi.ts',
    a: "    let vizitate = 0\n    for (const cs of ix.libere[zs]!) {\n      if (vizitate >= rules.haulDestMaxCells) break\n      vizitate++\n      raport.evaluariDestinatie++\n      const cx = c.wx[cs]!",
    b: "    let vizitate = 0\n    for (const cs of ix.libere[zs]!) {\n      if (vizitate >= rules.haulDestMaxCells) break\n      const cx = c.wx[cs]!",
    e2: [{ f: 'src/sim/joburi.ts', a: "      if (locPeCelula(w, rules, kind, cx, cy, cz) < cant) continue\n      // Aici NU se intinde niciun coridor de acoperire.", b: "      if (locPeCelula(w, rules, kind, cx, cy, cz) < cant) continue\n      vizitate++\n      raport.evaluariDestinatie++\n      // Aici NU se intinde niciun coridor de acoperire." }],
    t: 'tests/carat.test.ts', e: 'plafonul de destinatie numara INTRARI' },
  { n: 'celula de zona nu se retrage cand isi pierde podeaua', f: 'src/sim/joburi.ts',
    a: "  retrageCeluleDeZonaNecalcabile(w, rules, wx, wy, z + 1)\n", b: "",
    t: 'tests/carat.test.ts', e: 'o celula de depozit careia i se sapa podeaua' },
  { n: 'racirile de pe marfa supravietuiesc comenzii de zona', f: 'src/sim/commands.ts',
    a: '      // Premisa oricarui „n-are unde" tocmai s-a schimbat.\n      uitaRacirileDeMarfa(w)\n', b: '',
    t: 'tests/carat.test.ts', e: 'o comanda de zona sterge racirile' },
  { n: 'racirea pe marfa derivata din TOATE mormanele', f: 'src/sim/joburi.ts',
    a: "  return racireTinta(indexZone(w, rules).deMutat.length, rules)", b: "  return racireTinta(w.iteme.vii, rules)",
    t: 'tests/carat.test.ts', e: 'racirea pe marfa se deriva din cati CANDIDATI' },
  // Controlul garzii pe COST: reconstructia atinge sloturile MOARTE, nu doar pe
  // cele vii. E o regresie de cost adevarata (si exact forma pe care un
  // `it.capacity` scapat din greseala ar produce-o), iar `pasi` trebuie s-o vada.
  // Controlul de dinainte — „reconstruieste la fiecare scanare" — nu lega:
  // in acceptanta pionii sunt aproape mereu ocupati, deci 417 scanari in 6000 de
  // tickuri, si adauga 23 de reconstructii. Un control care nu misca numarul nu
  // probeaza nimic.
  { n: 'reconstructia atinge sloturile moarte (garda pe COST)', f: 'src/sim/zone.ts',
    a: "  for (let i = 0; i < it.count; i++) {\n    ix.pasi++", b: "  for (let i = 0; i < it.capacity; i++) {\n    ix.pasi++",
    t: 'tests/carat.test.ts', e: 'ACCEPTANTA' },
  { n: 'invariantul de carat scos din parseRules', f: 'src/sim/content.ts',
    a: "  if (discMic + r.jobRegionRadiusBlocks + 2 < blocuriDeDestinatie) {", b: "  if (discMic + r.jobRegionRadiusBlocks + 2 < 0 * blocuriDeDestinatie) {",
    t: 'tests/joburi.test.ts', e: 'content: discul agentului' },
  { n: 'marginea oarba la fel (maxPrioLibera un singur numar)', f: 'src/sim/zone.ts',
    a: "      const k = it.kind[item]!\n      const loc = rules.itemStackMax - it.cantitate[item]!\n      ix.libere[zs]!.push(cs)\n      ix.acceptante[zs * ITEME + k]!++\n      if (loc > ix.maxLocLiber[zs * ITEME + k]!) ix.maxLocLiber[zs * ITEME + k] = loc",
    b: "      const loc = rules.itemStackMax - it.cantitate[item]!\n      ix.libere[zs]!.push(cs)\n      for (let k = 0; k < ITEME; k++) {\n        ix.acceptante[zs * ITEME + k]!++\n        if (loc > ix.maxLocLiber[zs * ITEME + k]!) ix.maxLocLiber[zs * ITEME + k] = loc\n      }",
    t: 'tests/carat.test.ts', e: 'fara depozit' },
  { n: 'trecerea ieftina peste TOATE itemele, nu peste deMutat', f: 'src/sim/joburi.ts',
    a: "    for (const s of ix.deMutat) {\n      if (it.alive[s] === 0) continue", b: "    for (let s = 0; s < it.count; s++) {\n      if (it.alive[s] === 0) continue",
    t: 'tests/carat.test.ts', e: 'trecerea ieftina vede DOAR' },
  { n: 'racirea pe zona scoasa', f: 'src/sim/joburi.ts',
    // Re-ancorata: codul s-a mutat in `DRIVER_CARA.incheie` (alta indentare).
    a: "      if (cs !== -1) evitaTinta(w, slot, w.zone.celule.zonaId[cs]!, w.tick + rules.jobRetryTicks)\n", b: "",
    t: 'tests/carat.test.ts', e: 'drum peste buget spre depozit' },
  { n: 'strict-mai-bun scos (si zonele egale sunt destinatii)', f: 'src/sim/joburi.ts',
    a: "    if (prio <= prioLoc) break\n", b: "    if (prio < prioLoc) break\n",
    e2: [{ f: 'src/sim/zone.ts', a: "    if (ix.maxPrioLibera[it.kind[i]!]! > prioLoc && incapeUndeva(s, ix, it.kind[i]!, cant, prioLoc)) {", b: "    if (ix.maxPrioLibera[it.kind[i]!]! >= prioLoc && incapeUndeva(s, ix, it.kind[i]!, cant, prioLoc)) {" },
      // Si poarta din `incapeUndeva`, altfel ea singura pastreaza strict-mai-bun.
      { f: 'src/sim/zone.ts', a: "    if (s.prioritate[zs]! <= prioLoc) return false", b: "    if (s.prioritate[zs]! < prioLoc) return false" }],
    t: 'tests/carat.test.ts', e: 'strict mai bun' },
  { n: 'prioritatea locului ignorata (totul e „pe jos")', f: 'src/sim/joburi.ts',
    a: "    const prioLoc = prioritateaLocului(w.zone, ixx, iy, iz)", b: "    const prioLoc = 0",
    e2: [{ f: 'src/sim/zone.ts', a: "    const prioLoc = prioritateaLocului(s, it.wx[i]!, it.wy[i]!, it.z[i]!)", b: "    const prioLoc = 0" }],
    t: 'tests/carat.test.ts', e: 'strict mai bun' },
  { n: 'CARA evaluat doar cand SAPA nu da nimic', f: 'src/sim/joburi.ts',
    a: "  if (activ.cara) {\n    const gPers = 4 ** (persC - 1)", b: "  if (activ.cara && n === 0) {\n    const gPers = 4 ** (persC - 1)",
    t: 'tests/carat.test.ts', e: 'carieră + depozit' },
  { n: 'exclusiv: fiecare categorie la maxim sare peste celelalte', f: 'src/sim/joburi.ts',
    a: "    sapa: pS > 0 && (!exclusiv || pS === rules.personalPriorityLevels),\n    cara: pC > 0 && (!exclusiv || pC === rules.personalPriorityLevels),", b: "    sapa: pS > 0 && !(exclusiv && pC === rules.personalPriorityLevels),\n    cara: pC > 0 && !(exclusiv && pS === rules.personalPriorityLevels),",
    t: 'tests/carat.test.ts', e: 'exclusiv pe AMBELE' },
  { n: 'zavorul „fara progres" ignora jobEfect', f: 'src/sim/joburi.ts',
    a: "    if (a.jobProgres[slot] === 0 && a.jobEfect[slot] === 0) w.ratiune.joburiFaraProgres++", b: "    if (a.jobProgres[slot] === 0) w.ratiune.joburiFaraProgres++",
    t: 'tests/carat.test.ts', e: 'drum peste buget spre depozit' },
  { n: 'caraCantitate nu se salveaza', f: 'src/sim/save.ts',
    a: "        caraCantitate: Array.from(a.caraCantitate.subarray(0, a.count)),", b: "        caraCantitate: new Array(a.count).fill(0),",
    t: 'tests/carat.test.ts', e: 'M5 in cei PATRU pasi' },
  { n: 'jobCantitate nu se salveaza', f: 'src/sim/save.ts',
    a: "        jobCantitate: Array.from(a.jobCantitate.subarray(0, a.count)),", b: "        jobCantitate: new Array(a.count).fill(0),",
    t: 'tests/carat.test.ts', e: 'M5 in cei PATRU pasi' },
  { n: 'racirea pe item nu se salveaza', f: 'src/sim/save.ts',
    a: "        reincercaLaTick: Array.from(it.reincercaLaTick.subarray(0, it.count)),", b: "        reincercaLaTick: new Array(it.count).fill(0),",
    t: 'tests/carat.test.ts', e: 'M5 in cei PATRU pasi' },
  { n: 'prioritatea zonei nu intra in hash', f: 'src/sim/hash.ts',
    a: "  h.bytes(z.prioritate, z.count)\n", b: "",
    t: 'tests/carat.test.ts', e: 'hash-ul vede FIECARE camp PERSISTED nou al taieturii 2' },
  { n: 'cantitatea itemului nu intra in hash', f: 'src/sim/hash.ts',
    a: "  h.ints(it.cantitate, it.count)\n", b: "",
    t: 'tests/carat.test.ts', e: 'hash-ul vede FIECARE camp PERSISTED nou al taieturii 2' },
  { n: 'migrarea nu largeste prioPersonala (categorii ignorat)', f: 'src/sim/save.ts',
    a: "    const k = (agentsRaw.categorii as number | undefined) ?? 1", b: "    const k = CATEGORII",
    t: 'tests/migrare.test.ts', e: 'migrarea 3 -> 4: joburile' },
  { n: 'doua iteme pe o celula trec la load', f: 'src/sim/iteme.ts',
    a: "    if (s.laCelula.has(key)) {\n      return refuse(Reason.CELULA_OCUPATA, { camp: 'iteme'", b: "    if (s.laCelula.size < 0) {\n      return refuse(Reason.CELULA_OCUPATA, { camp: 'iteme'",
    t: 'tests/iteme.test.ts', e: 'un save cu doua iteme vii' },
  { n: 'elibereazaUna elibereaza toata perechea', f: 'src/sim/rezervari.ts',
    a: "  const k = cheieRezervare(targetId, layer)\n  const lista = s.peTinta.get(k)\n  if (!lista) return 0\n  const ramase = lista.filter((r) => !(r.claimant === claimant && r.jobId === jobId))\n  const eliberate = lista.length - ramase.length\n  if (eliberate === 0) return 0\n  if (ramase.length === 0) s.peTinta.delete(k)\n  else s.peTinta.set(k, ramase)\n  s.total -= eliberate\n  return eliberate",
    b: "  void targetId; void layer\n  return elibereaza(s, claimant, jobId)",
    t: 'tests/rezervari.test.ts', e: 'elibereazaUna scoate DOAR' },
  { n: 'clauza „tinta exista" scoasa', f: 'src/sim/rezervari.ts',
    a: "      if (existaTinta && !existaTinta(r.targetId, r.layer)) {", b: "      if (existaTinta && false) {",
    t: 'tests/rezervari.test.ts', e: 'INVARIANT: clauza' },
  { n: 'yield-ul nu se produce', f: 'src/sim/joburi.ts',
    a: "  if (y && y.cantitate > 0) {\n    asazaItem(w, rules, y.fel, y.cantitate, wx, wy, z)", b: "  if (y && y.cantitate < 0) {\n    asazaItem(w, rules, y.fel, y.cantitate, wx, wy, z)",
    t: 'tests/iteme.test.ts', e: 'sapatul PRODUCE' },
  { n: 'capacitatea de transport ignorata', f: 'src/sim/joburi.ts',
    a: "      const cant = Math.min(it.cantitate[s]!, rules.haulCarryMax)\n      if (!poateRezerva", b: "      const cant = it.cantitate[s]!\n      if (!poateRezerva",
    e2: [{ f: 'src/sim/joburi.ts', a: "    const cant = Math.min(it.cantitate[s]!, rules.haulCarryMax)\n    const prioLoc", b: "    const cant = it.cantitate[s]!\n    const prioLoc" }],
    t: 'tests/carat.test.ts', e: 'capacitatea de transport LEAGA' },
  { n: 'anularea de la incarcare nu lasa marfa la picioare', f: 'src/sim/joburi.ts',
    a: "    if (a.alive[i] === 1) {\n      lasaLaPicioare(w, rules, i)\n    } else {",
    b: "    if (a.alive[i] === 2) {\n      lasaLaPicioare(w, rules, i)\n    } else {",
    t: 'tests/carat.test.ts', e: 'un save cu un job de carat orfan' },
]
