/**
 * Mutatii: grinda (S20-23, taietura 4).
 *
 * Intai indexul DERIVED al grinzilor: tinut la zi in `editAt`, reconstruit la
 * incarcare. Un index care se desincronizeaza nu e un cost in plus — pe el se
 * sprijina regula, deci ar fi fizica diferita intre lumea continua si cea incarcata.
 *
 * Apoi regula stratificata: `s1` din grinzile ACTIVE, discurile de invalidare (a, b,
 * c), multimea care cade calculata INAINTE de sapat, memoria activitatii si coada
 * deduplicata (cele doua din urma sunt cost, nu corectitudine: le prind plafoanele
 * K05), grinzile planificate ale inchiderii, prefiltrul overlay-ului si „De ce nu?".
 * Si scanarea overlay-ului, feliata pe cadre de la grinda: bugetul, cursorul, repornirea.
 */

export const MUTATII = [
  {
    n: 'indexul nu scoate grinda sapata (ramane o grinda-fantoma in lumea continua)',
    f: 'src/sim/terrain/terrain.ts',
    a: '  if (current.value === Material.GRINDA) scoateGrinda(t.grinzi, wx, wy, z)',
    b: '  void scoateGrinda',
    t: 'tests/grinda.test.ts', e: 'indexul de grinzi e DERIVED',
  },
  {
    n: 'indexul nu vede grinda zidita',
    f: 'src/sim/terrain/terrain.ts',
    a: '  if (material === Material.GRINDA) adaugaGrinda(t.grinzi, wx, wy, z)',
    b: '  void adaugaGrinda',
    t: 'tests/grinda.test.ts', e: 'indexul de grinzi e DERIVED',
  },
  {
    n: 'indexul nu se reconstruieste la incarcare (lumea incarcata n-are grinzi)',
    f: 'src/sim/save.ts',
    a: '  reconstruiesteGrinzi(terrain)',
    b: '  void reconstruiesteGrinzi',
    t: 'tests/grinda.test.ts', e: 'indexul de grinzi e DERIVED',
  },
  {
    n: 'lista unui chunk ramasa goala nu se sterge (indexul continuu difera ca forma de cel reconstruit)',
    f: 'src/sim/terrain/terrain.ts',
    a: '  if (lista.length === 0) index.delete(ck)',
    b: '  void ck',
    t: 'tests/grinda.test.ts', e: 'indexul de grinzi e DERIVED',
  },
  {
    n: 's1 ignorat la propagare: tot ce sta prin grinzi cade in previzualizare, nu si in oracol',
    f: 'src/sim/stabilitate.ts',
    a: '    : caveazaSpreAsezat(t, rules, wx, wy, z, ip.cazute, ip.zidite)\n  if (s0 >= plafon) return plafon\n  return Math.min(plafon, Math.max(s0, suportDinGrinzi(t, rules, wx, wy, z, ip)))',
    b: '    : caveazaSpreAsezat(t, rules, wx, wy, z, ip.cazute, ip.zidite)\n  if (s0 >= plafon) return plafon\n  return Math.min(plafon, s0)',
    t: 'tests/grinda.test.ts', e: 'PROPRIETATE: pe scene aleatoare',
  },
  {
    n: 's1 ignorat la zidire: grinda nu mai duce fasia dincolo de 3',
    f: 'src/sim/stabilitate.ts',
    a: '    : caveazaSpreAsezat(t, rules, wx, wy, z, null, ip.zidite)\n  if (s0 >= plafon) return plafon\n  return Math.min(plafon, Math.max(s0, suportDinGrinzi(t, rules, wx, wy, z, ip)))',
    b: '    : caveazaSpreAsezat(t, rules, wx, wy, z, null, ip.zidite)\n  if (s0 >= plafon) return plafon\n  return Math.min(plafon, s0)',
    t: 'tests/grinda.test.ts', e: 'fasia din zid',
  },
  {
    n: 'orice grinda in picioare e activa (una plutitoare tine podeaua)',
    f: 'src/sim/stabilitate.ts',
    a: '  return inPicioare.has(k) && activa(t, rules, x, y, z, ip)',
    b: '  return inPicioare.has(k)',
    t: 'tests/grinda.test.ts', e: 'o grinda plutitoare nu tine nimic',
  },
  {
    n: 'candidatul nu trebuie sa fie din material GRINDA (intrarea veche din index devine grinda-fantoma)',
    f: 'src/sim/stabilitate.ts',
    a: '  return materialFast(t, x, y, z) === Material.GRINDA',
    b: '  return true',
    t: 'tests/grinda.test.ts', e: 'o intrare VECHE in index',
  },
  {
    n: 'activitatea nu se memoreaza (un BFS per candidat per interogare)',
    f: 'src/sim/stabilitate.ts',
    a: '  if (ip.activ !== null) ip.activ.set(k, a)',
    b: '  void k',
    t: 'tests/grinda.test.ts', e: 'K05: o grinda departe',
  },
  {
    n: 'inchiderea nu mai invalideaza memoria la zidire (o grinda activata mai tarziu de plan ramane inactiva)',
    f: 'src/sim/stabilitate.ts',
    a: '      zidite.add(cheie)\n      invalideaza(cheie)',
    b: '      zidite.add(cheie)',
    t: 'tests/grinda.test.ts', e: 'S6e: o grinda care se DEZACTIVEAZA',
  },
  {
    n: 'invalidarea inchiderii pe raza suportMax - 2',
    f: 'src/sim/stabilitate.ts',
    a: '        grinziInRaza(index, cz.wx, cz.wy, cz.z + dz, rules.suportMax - 1, lista)',
    b: '        grinziInRaza(index, cz.wx, cz.wy, cz.z + dz, rules.suportMax - 2, lista)',
    t: 'tests/grinda.test.ts', e: 'inchiderea: o grinda zidita INACTIVA',
  },
  {
    n: 'invalidarea inchiderii doar la cota de deasupra (nu si la cota zidirii)',
    f: 'src/sim/stabilitate.ts',
    a: '    decodeCellIn(k, cz)\n    for (const dz of [0, 1]) {',
    b: '    decodeCellIn(k, cz)\n    for (const dz of [1]) {',
    t: 'tests/grinda.test.ts', e: 'inchiderea: o grinda zidita INACTIVA',
  },
  {
    n: 'invalidarea inchiderii doar la cota zidirii (celula de deasupra devine asezata, grinda de acolo nu afla)',
    f: 'src/sim/stabilitate.ts',
    a: '    decodeCellIn(k, cz)\n    for (const dz of [0, 1]) {',
    b: '    decodeCellIn(k, cz)\n    for (const dz of [0]) {',
    t: 'tests/grinda.test.ts', e: 'inchiderea: o grinda zidita INACTIVA',
  },
  {
    n: 'un candidat din PLAN nu mai e grinda (sursa lui se pierde in forma lenesa)',
    f: 'src/sim/stabilitate.ts',
    a: '    if (!grindaInPicioare(t, x, y, z, ip, i >= dinTeren)) continue',
    b: '    if (!grindaInPicioare(t, x, y, z, ip, false)) continue',
    t: 'tests/grinda.test.ts', e: 'inchiderea de constructie cu grinzi PLANIFICATE',
  },
  {
    n: 'activitatea TUTUROR candidatilor, ca inainte de recenzie (un santier fara drum plateste ~180 de BFS-uri)',
    f: 'src/sim/stabilitate.ts',
    a: '  const k0 = cellKey(wx, wy, z)\n  if (candidatActiv(t, rules, wx, wy, z, k0, ip)) return R',
    b: '  for (let i = 0; i < candidati.length; i += 2) candidatActiv(t, rules, candidati[i]!, candidati[i + 1]!, z, cellKey(candidati[i]!, candidati[i + 1]!, z), ip)\n  const k0 = cellKey(wx, wy, z)\n  if (candidatActiv(t, rules, wx, wy, z, k0, ip)) return R',
    t: 'tests/grinda.test.ts', e: 'K05: poarta scanerului',
  },
  {
    n: 'memoria portii nu se goleste la editare (santierul ramane cu raspunsul vechi)',
    f: 'src/sim/stabilitate.ts',
    a: '  if (m.teren !== t || m.rules !== rules || m.editari !== t.editari) {',
    b: '  if (m.teren !== t || m.rules !== rules) {',
    t: 'tests/grinda.test.ts', e: 'poarta scanerului, din memorie',
  },
  {
    n: 'memoria portii ignora TERENUL (alt teren cu aceeasi epoca primeste raspunsul primului)',
    f: 'src/sim/stabilitate.ts',
    a: '  if (m.teren !== t || m.rules !== rules || m.editari !== t.editari) {',
    b: '  if (m.rules !== rules || m.editari !== t.editari) {',
    t: 'tests/grinda.test.ts', e: 'poarta scanerului, din memorie',
  },
  {
    n: 'memoria portii ignora REGULILE',
    f: 'src/sim/stabilitate.ts',
    a: '  if (m.teren !== t || m.rules !== rules || m.editari !== t.editari) {',
    b: '  if (m.teren !== t || m.editari !== t.editari) {',
    t: 'tests/grinda.test.ts', e: 'poarta scanerului, din memorie',
  },
  {
    n: 'memoria portii uita raspunsurile, dar nu si activitatea grinzilor (o grinda activata ramane „inactiva")',
    f: 'src/sim/stabilitate.ts',
    a: '    m.activ.clear()',
    b: '    void m.activ',
    t: 'tests/grinda.test.ts', e: 'poarta scanerului, din memorie',
  },
  {
    n: 'poarta scanerului fara memoria activitatii (fiecare santier recalculeaza grinzile)',
    f: 'src/sim/stabilitate.ts',
    a: '  const r = sustinutAcum(t, rules, wx, wy, z, m.activ)',
    b: '  const r = sustinutAcum(t, rules, wx, wy, z, null)',
    t: 'tests/grinda.test.ts', e: 'K05: poarta scanerului',
  },
  {
    n: 'poarta scanerului fara memoria raspunsurilor (fiecare scanare re-intreaba fiecare santier)',
    f: 'src/sim/stabilitate.ts',
    a: '  const stiut = m.ok.get(k)\n  if (stiut !== undefined) return stiut',
    b: '  void k',
    t: 'tests/grinda.test.ts', e: 'K05: poarta scanerului',
  },
  {
    n: 'editAt nu numara editarea: epoca terenului sta pe loc, iar consola pionilor se opreste la prima celula',
    f: 'src/sim/terrain/terrain.ts',
    a: '  t.editari++',
    b: '  void t',
    t: 'tests/constructie.test.ts', e: 'pionii ridica o CONSOLA din zid',
  },
  {
    n: 'inchiderea ignora grinzile planificate',
    f: 'src/sim/stabilitate.ts',
    a: 'grinziPlan: grinzi.length > 0 ? plan : null',
    b: 'grinziPlan: null',
    t: 'tests/grinda.test.ts', e: 'inchiderea de constructie cu grinzi PLANIFICATE',
  },
  {
    n: 'coada din propaga nu se deduplica',
    f: 'src/sim/stabilitate.ts',
    a: '    if (inAsteptare.has(k)) return',
    b: '    if (inAsteptare.size < 0) return',
    t: 'tests/grinda.test.ts', e: 'K05: o grinda departe',
  },
  {
    n: 'discul (a) lipseste: grinda care cade nu re-verifica ce tinea',
    f: 'src/sim/stabilitate.ts',
    a: '    if (materialFast(t, x, y, z) === Material.GRINDA) discGrinda(x, y, z)',
    b: '    void Material',
    t: 'tests/grinda.test.ts', e: 'S6d: sapi grinda',
  },
  {
    n: 'discul (b) lipseste: grinzile care se dezactiveaza nu re-verifica ce tineau',
    f: 'src/sim/stabilitate.ts',
    a: '        if (activa(t, rules, bx, by, bz, ip) !== anterior) discGrinda(bx, by, bz)',
    b: '        activa(t, rules, bx, by, bz, ip)',
    t: 'tests/grinda.test.ts', e: 'S6e: o grinda care se DEZACTIVEAZA',
  },
  {
    n: 'discul (b) fara conditie: fiecare grinda din preajma isi emite discul',
    f: 'src/sim/stabilitate.ts',
    a: '        if (activa(t, rules, bx, by, bz, ip) !== anterior) discGrinda(bx, by, bz)',
    b: '        if (activa(t, rules, bx, by, bz, ip) !== anterior || true) discGrinda(bx, by, bz)',
    t: 'tests/grinda.test.ts', e: 'K05: o grinda departe',
  },
  {
    n: 'memoria activitatii nu se goleste la cadere (activitatea veche ascunde dezactivarea)',
    f: 'src/sim/stabilitate.ts',
    a: '        if (!samanta) activ.delete(kb)',
    b: '        void samanta',
    t: 'tests/grinda.test.ts', e: 'S6e: o grinda care se DEZACTIVEAZA',
  },
  {
    n: 'activitatea dinaintea sapaturii nu se tine minte (samanta nu schimba nimic, in aparenta)',
    f: 'src/sim/stabilitate.ts',
    a: '        let anterior = samanta ? (inainte.get(kb) ?? false) : activ.get(kb)',
    b: '        let anterior = samanta ? s0Pozitiv(t, rules, bx, by, bz, ip) : activ.get(kb)',
    t: 'tests/grinda.test.ts', e: 'S6e: o grinda care se DEZACTIVEAZA',
  },
  {
    n: 'discul (c) lipseste: un drum spre o grinda activa care trecea prin celula cazuta',
    f: 'src/sim/stabilitate.ts',
    a: '      discGrinda(x, y, z)\n      break',
    b: '      break',
    t: 'tests/grinda.test.ts', e: 'PROPRIETATE: pe scene aleatoare',
  },
  {
    n: 'multimea care cade se calculeaza DUPA sapat (grinda sapata a iesit deja din index)',
    f: 'src/sim/joburi.ts',
    a: '  const cad = multimeaCareCade(w.terrain, rules, wx, wy, z)\n  const out = dig(w.terrain, wx, wy, z)\n  if (!out.ok) return out',
    b: '  const out = dig(w.terrain, wx, wy, z)\n  if (!out.ok) return out\n  const cad = multimeaCareCade(w.terrain, rules, wx, wy, z)',
    t: 'tests/grinda.test.ts', e: 'S6d: sapi grinda',
  },
  {
    n: 'grinziInRaza nu taie chunk-urile la lume (grinda de la est apare la vest)',
    f: 'src/sim/terrain/terrain.ts',
    a: '  const cx0 = Math.max(0, Math.floor((wx - raza) / CHUNK_CELLS))',
    b: '  const cx0 = Math.floor((wx - raza) / CHUNK_CELLS)',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza: doar cota ceruta',
  },
  {
    n: 'grinziInRaza intoarce si cota de deasupra',
    f: 'src/sim/terrain/terrain.ts',
    a: '      const sus = cheieLocala(CHUNK_CELLS - 1, lyMax, z)',
    b: '      const sus = cheieLocala(CHUNK_CELLS - 1, lyMax, z + 1)',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza: doar cota ceruta',
  },
  {
    n: 'grinziInRaza nu filtreaza pe Manhattan (intoarce cutia)',
    f: 'src/sim/terrain/terrain.ts',
    a: '        if (Math.abs(x - wx) + Math.abs(y - wy) <= raza) out.push(x, y)',
    b: '        out.push(x, y)',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza: doar cota ceruta',
  },
  {
    n: 'prefiltrul ramane pe raza de sol si langa grinzi',
    f: 'src/sim/stabilitate.ts',
    a: '  const raza = aproape.length > 0 ? Math.max(rules.suportMax, rules.suportRazaGrinda) : rules.suportMax',
    b: '  const raza = rules.suportMax',
    t: 'tests/grinda.test.ts', e: 'prefiltrul overlay-ului: langa o grinda',
  },
  {
    n: 'prefiltrul cauta grinzi doar in fereastra (nu si pe cele din afara, care tin celule din ea)',
    f: 'src/sim/stabilitate.ts',
    a: '  grinziInRaza(t.grinzi, x0 + jum, y0 + jum, zA, 2 * jum + rules.suportRazaGrinda, aproape)',
    b: '  grinziInRaza(t.grinzi, x0 + jum, y0 + jum, zA, jum, aproape)',
    t: 'tests/grinda.test.ts', e: 'prefiltrul overlay-ului: langa o grinda',
  },
  {
    n: '„De ce nu?" spune mereu ca grinda din raza e activa',
    f: 'src/sim/stabilitate.ts',
    a: 'grindaActiva: eActiva ? 1 : 0,',
    b: 'grindaActiva: 1,',
    t: 'tests/grinda.test.ts', e: '„De ce nu?" deosebeste',
  },
  {
    n: 'scanarea overlay-ului ignora bugetul (o trecere de secunde intr-un singur cadru)',
    f: 'viewer/scanare-stabilitate.ts',
    a: '    if (ceas() - t0 >= buget) break',
    b: '    void buget',
    t: 'tests/scanare-stabilitate.test.ts', e: 'bugetul se respecta',
  },
  {
    n: 'trecerea din curs nu se reporneste nici pentru alta raza',
    f: 'viewer/scanare-stabilitate.ts',
    a: '  return s.zActiv === zActiv && s.cx === cx && s.cy === cy && s.raza === raza',
    b: '  return s.zActiv === zActiv && s.cx === cx && s.cy === cy',
    t: 'tests/scanare-stabilitate.test.ts', e: 'trecerea din curs nu se reporneste',
  },
  {
    n: 'scanarea feliata judeca alta celula decat cea din filtru',
    f: 'viewer/scanare-stabilitate.ts',
    a: '    const wy = y0 + (k % lat)',
    b: '    const wy = y0 + Math.floor(k / lat)',
    t: 'tests/scanare-stabilitate.test.ts', e: 'felierea nu schimba trecerea',
  },
  {
    n: 'grinda ASEZATA (pe un stalp, fara vecin asezat) nu mai e activa',
    f: 'src/sim/stabilitate.ts',
    a: '  if (esteAsezat(t, x, y, z, ip.cazute, ip.zidite)) return true\n  return caveazaSpreAsezat',
    b: '  return caveazaSpreAsezat',
    t: 'tests/grinda.test.ts', e: 'placa peste un stalp',
  },
  {
    n: 'celula care E o grinda activa nu primeste suportRazaGrinda (suportLa inexact)',
    f: 'src/sim/stabilitate.ts',
    a: '  if (candidatActiv(t, rules, wx, wy, z, k0, ip)) return R\n',
    b: '  void k0\n',
    t: 'tests/grinda.test.ts', e: 'suportLa e EXACT langa grinzi',
  },
  {
    n: 'activitatea de dinaintea sapaturii se tine minte doar la cota samantei, nu si la z+1',
    f: 'src/sim/stabilitate.ts',
    a: '    decodeCellIn(e, cg)\n    for (const dz of [0, 1]) {',
    b: '    decodeCellIn(e, cg)\n    for (const dz of [0]) {',
    t: 'tests/grinda.test.ts', e: 'discul (b) pe fiecare ramura',
  },
  {
    n: 'activitatea de dinaintea sapaturii: raza suportMax - 2 (grinda la distanta 3 scapa)',
    f: 'src/sim/stabilitate.ts',
    a: '      grinziInRaza(t.grinzi, cg.wx, cg.wy, cg.z + dz, rules.suportMax - 1, lista)',
    b: '      grinziInRaza(t.grinzi, cg.wx, cg.wy, cg.z + dz, rules.suportMax - 2, lista)',
    t: 'tests/grinda.test.ts', e: 'discul (b) pe fiecare ramura',
  },
  {
    n: 'discul (b) cauta grinzile pe raza suportMax - 2',
    f: 'src/sim/stabilitate.ts',
    a: '      grinziInRaza(t.grinzi, x, y, z + dz, rules.suportMax - 1, lista)',
    b: '      grinziInRaza(t.grinzi, x, y, z + dz, rules.suportMax - 2, lista)',
    t: 'tests/grinda.test.ts', e: 'discul (b) pe fiecare ramura',
  },
  {
    n: 'in cascada, activitatea „de dinainte" se calculeaza cu k deja cazut (starea de dupa)',
    f: 'src/sim/stabilitate.ts',
    a: '          cazute.delete(k)\n          anterior = s0Pozitiv(t, rules, bx, by, bz, ip)\n          cazute.add(k)',
    b: '          anterior = s0Pozitiv(t, rules, bx, by, bz, ip)',
    t: 'tests/grinda.test.ts', e: 'discul (b) pe fiecare ramura',
  },
  {
    n: 'cheia locala a indexului nu mai deplaseaza cota (cotele negative se decodeaza gresit)',
    f: 'src/sim/terrain/terrain.ts',
    a: 'const Z_GRINDA = 1024',
    b: 'const Z_GRINDA = 0',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza = forta bruta',
  },
  {
    n: 'grinziInRaza pierde coloana lx = 31 de pe ultimul rand al intervalului',
    f: 'src/sim/terrain/terrain.ts',
    a: '      const sus = cheieLocala(CHUNK_CELLS - 1, lyMax, z)',
    b: '      const sus = cheieLocala(CHUNK_CELLS - 2, lyMax, z)',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza = forta bruta',
  },
  {
    n: 'grinziInRaza pierde coloana lx = 0 de pe primul rand al intervalului',
    f: 'src/sim/terrain/terrain.ts',
    a: '      for (let i = pozitie(lista, cheieLocala(0, lyMin, z)); i < lista.length',
    b: '      for (let i = pozitie(lista, cheieLocala(1, lyMin, z)); i < lista.length',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza = forta bruta',
  },
  {
    n: 'grinziInRaza: cy1 cu un chunk mai putin cand raza se termina pe granita',
    f: 'src/sim/terrain/terrain.ts',
    a: '  const cy1 = Math.min(CHUNK_GRID - 1, Math.floor((wy + raza) / CHUNK_CELLS))',
    b: '  const cy1 = Math.min(CHUNK_GRID - 1, Math.floor((wy + raza - 1) / CHUNK_CELLS))',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza = forta bruta',
  },
  {
    n: 'grinziInRaza: cx0 cu un chunk mai putin cand raza se termina pe granita',
    f: 'src/sim/terrain/terrain.ts',
    a: '  const cx0 = Math.max(0, Math.floor((wx - raza) / CHUNK_CELLS))',
    b: '  const cx0 = Math.max(0, Math.floor((wx - raza + 1) / CHUNK_CELLS))',
    t: 'tests/grinda.test.ts', e: 'grinziInRaza = forta bruta',
  },
  {
    n: 'scanarea overlay-ului calculeaza filtrul pe o fereastra decalata cu o celula',
    f: 'viewer/scanare-stabilitate.ts',
    a: '    filtru: prefiltruStabilitate(w.terrain, rules, cx - raza, cy - raza, lat, zActiv),',
    b: '    filtru: prefiltruStabilitate(w.terrain, rules, cx - raza + 1, cy - raza, lat, zActiv),',
    t: 'tests/scanare-stabilitate.test.ts', e: 'felierea nu schimba trecerea',
  },  {
    n: 'samanta ia starea „de dinainte" din memorie cand o are (previzualizarea depinde de ordinea sapaturilor)',
    f: 'src/sim/stabilitate.ts',
    a: '        let anterior = samanta ? (inainte.get(kb) ?? false) : activ.get(kb)',
    b: '        let anterior = activ.get(kb) ?? (samanta ? (inainte.get(kb) ?? false) : undefined)',
    t: 'tests/grinda.test.ts', e: 'previzualizarea pe MAI MULTE sapaturi nu depinde de ordinea lor',
  },  {
    n: 's1 sare peste grinzile a caror activitate nu e inca stiuta (iesirea timpurie cere „stiuta activa")',
    f: 'src/sim/stabilitate.ts',
    a: '    if (ip.activ?.get(k) !== false) deIncercat = true',
    b: '    if (ip.activ?.get(k) === true) deIncercat = true',
    t: 'tests/grinda.test.ts', e: 'fasia din zid',
  },  {
    n: 'prefiltrul nu mai largeste fereastra: grinda de langa margine tine un tavan de dincolo, nevazut',
    f: 'src/sim/stabilitate.ts',
    a: '  const m = raza\n  const L = lat + 2 * m',
    b: '  const m = 0\n  const L = lat + 2 * m',
    t: 'tests/prefiltru.test.ts', e: 'marginea: o grinda la 1..4 pasi de margine',
  },
  {
    n: 'prefiltrul cauta grinzile doar in rombul ferestrei (2·jum, fara raza grinzii)',
    f: 'src/sim/stabilitate.ts',
    a: '  grinziInRaza(t.grinzi, x0 + jum, y0 + jum, zA, 2 * jum + rules.suportRazaGrinda, aproape)',
    b: '  grinziInRaza(t.grinzi, x0 + jum, y0 + jum, zA, 2 * jum, aproape)',
    t: 'tests/prefiltru.test.ts', e: 'cautarea grinzilor',
  },  {
    n: 'cererea periodica reporneste si trecerea din curs (langa grinzi nu se mai termina niciodata)',
    f: 'viewer/scanare-stabilitate.ts',
    a: '  if (inCurs !== null && aceeasiScanare(inCurs, zActiv, cx, cy, raza)) return Trecere.CONTINUA',
    b: '  void inCurs',
    t: 'tests/scanare-stabilitate.test.ts', e: 'cererea periodica nu reporneste trecerea din curs',
  },
  {
    n: 'o trecere terminata ramane „gata" si dupa o editare de teren (desen vechi pe teren nou)',
    f: 'viewer/scanare-stabilitate.ts',
    a: '&& ultima.teren === teren && ultima.editari === teren.editari) return Trecere.GATA',
    b: '&& ultima.teren === teren) return Trecere.GATA',
    t: 'tests/scanare-stabilitate.test.ts', e: 'cererea periodica nu reporneste trecerea din curs',
  },
  {
    n: 'o trecere terminata ramane „gata" pe ALT teren (alta lume, aceeasi epoca)',
    f: 'viewer/scanare-stabilitate.ts',
    a: '&& ultima.teren === teren && ultima.editari === teren.editari) return Trecere.GATA',
    b: '&& ultima.editari === teren.editari) return Trecere.GATA',
    t: 'tests/scanare-stabilitate.test.ts', e: 'cererea periodica nu reporneste trecerea din curs',
  },  {
    n: 'memoria activitatii tine doar „activa" (forma de dinainte de COST-2: grinzile inactive se recalculeaza la fiecare interogare)',
    f: 'src/sim/stabilitate.ts',
    a: '  if (ip.activ !== null) ip.activ.set(k, a)',
    b: '  if (ip.activ !== null && a) ip.activ.set(k, a)',
    t: 'tests/grinda.test.ts', e: 'K05: cascada, inchiderea si previzualizarea',
  },
  {
    n: 'memoria activitatii se goleste si la insamantare (COST-3: 10.310 de BFS-uri in loc de 882)',
    f: 'src/sim/stabilitate.ts',
    a: '        if (!samanta) activ.delete(kb)',
    b: '        activ.delete(kb)',
    t: 'tests/grinda.test.ts', e: 'K05: cascada, inchiderea si previzualizarea',
  },
  {
    n: 'stareSapat nu se mai opreste la prima cadere (baza unui stalp cu etaje: 6 -> 1.583 de verificari)',
    f: 'src/sim/stabilitate.ts',
    a: '    if (laPrimaCadere) return { cazute, minim }',
    b: '    void laPrimaCadere',
    t: 'tests/grinda.test.ts', e: 'K05: cascada, inchiderea si previzualizarea',
  },
  {
    n: 'discul grinzii are raza R in loc de R - 1 (verificari in plus pe fiecare sapatura langa grinzi)',
    f: 'src/sim/stabilitate.ts',
    a: '    disc(x, y, z, R - 1, dinDisc)',
    b: '    disc(x, y, z, R, dinDisc)',
    t: 'tests/grinda.test.ts', e: 'K05: o grinda departe',
  },
  {
    n: 'contorul interogarilor s1 nu mai numara (prima parte a K05 devine vida)',
    f: 'src/sim/stabilitate.ts',
    a: '  contoareStabilitate.interogariS1++',
    b: '  void contoareStabilitate',
    t: 'tests/grinda.test.ts', e: 'K05: o grinda departe',
  },
]
