/**
 * Mutatii: temperatura ca STARE — S24-27 t.2b, valul 1, commit-urile 4 si 5 (research/temperatura-t2b.md §1, §2, §5, §7, §9).
 *
 * Commit-ul 4: punctul unic de sincronizare (src/sim/temperatura.ts, world.ts, commands.ts), invariantii (stampila
 * completa, T in ambele directii, refuzul fara aruncare), pasul de 1 Hz in forma ψ (muchiile din T vechi, oamenii, T*,
 * marginea dinamica, comutatorul BigInt, modelul memorat), echilibrul „lumii fara istorie". Le prind testele pe hartie
 * (tests/pas-termic.test.ts, tests/stare-temperatura.test.ts) si oracolele: referinta independenta a pasului pe BigInt,
 * Number == BigInt, orientarea inversata, punctul fix.
 *
 * Plasa de siguranta (recenzia PROV-1 b): C3 are o pompa incrucisata, deci un exploit deliberat poate urca T-ul fara
 * limita; dupa provenienta si dupa pas T se taie la ±1000 °C, numarat (taieri + invariant). O prind exploitul K=24 cu
 * timpul pornit (stare) si divergenta celulei-cruce (pas).
 */

const TP = 'tests/pas-termic.test.ts'
const TS = 'tests/stare-temperatura.test.ts'
const TSV = 'tests/salvare-temperatura.test.ts'
const F = 'src/sim/temperatura.ts'

export const MUTATII = [
  // --- punctul unic si invariantii (§2)
  {
    n: 't.2b §2: sincronizeazaLumea nu verifica stampila la intrare (o ocolire a punctului unic trece neobservata)',
    f: F,
    a: '  const intrare = verificaStampila(w)',
    b: '  const intrare = accept()',
    t: TS, e: 'STARE ocolirea punctului unic',
  },
  {
    n: 't.2b §2, IDX-2: stampila doar pe epoca (un lot doar-fete ocolit trece)',
    f: F,
    a: '  if (s.vazute !== idx.vazute || s.epoca !== idx.epoca || s.epocaFete !== idx.epocaFete) {',
    b: '  if (s.epoca !== idx.epoca) {',
    t: TS, e: 'STARE perechea (epoca, epocaFete)',
  },
  {
    n: 't.2b §2, IDX-6: stampila fara identitatea indexului (un index inlocuit cu aceleasi contoare trece)',
    f: F,
    a: '  if (s.idx !== idx) return refuse(',
    b: '  if (s.idx !== idx && false) return refuse(',
    t: TS, e: 'STARE indexul inlocuit',
  },
  {
    n: 't.2b §1, IDX-6: T intr-o singura directie — o componenta vie fara T nu se vede',
    f: F,
    a: '  if (cuT !== idx.comp.size) {',
    b: '  if (false) {',
    t: TS, e: 'STARE T in ambele directii',
  },
  {
    n: 't.2b §1, IDX-6: T intr-o singura directie — un slot mort cu T nu se vede',
    f: F,
    a: '    if (!idx.comp.has(s)) return refuse(',
    b: '    if (false) return refuse(',
    t: TS, e: 'STARE T in ambele directii',
  },
  {
    n: 't.2b §5.3: invariantii nu se numara',
    f: F,
    a: '  st.stat.invarianti++',
    b: '  void 0',
    t: TS, e: 'STARE ocolirea punctului unic',
  },
  {
    n: 't.2b §7: encode nu verifica temperatura (o stare ocolita se salveaza)',
    f: 'src/sim/save.ts',
    a: '  const t = temperaturaLaZi(w)',
    b: '  const t = { ok: true }',
    t: TS, e: 'STARE ocolirea punctului unic',
  },
  {
    n: 't.2b §7: decode fara echilibru (lumea incarcata are componente fara T)',
    f: 'src/sim/save.ts',
    a: '  const echilibru = temperaturaLaEchilibru(w, rules, w.tick)',
    b: '  const echilibru = { ok: true }',
    t: TS, e: 'STARE migrarea',
  },
  {
    n: 't.2b §7, SAV-11: buildM10PeLume fara echilibru (asezarea ramane pe proveninta NEC a recalculului)',
    f: 'src/harness/fixture-m10.ts',
    a: '  const e = temperaturaLaEchilibru(w, rules, w.tick)',
    b: '  const e = { ok: true }',
    t: 'tests/fixture.test.ts', e: 'M10 pe o LUME (gate-ul viewer-ului, IDX-5)',
  },
  {
    n: 't.2b §2, SAV-7: sincronizeazaLumea nu aplica proveninta (T-ul consumatorului ramane pe sloturile vechi)',
    f: F,
    a: '  if (sch.mase.noi.length > 0 || sch.moarte.length > 0) {',
    b: '  if (false) {',
    t: 'tests/provenienta.test.ts', e: 'PROVENIENTA prin COMENZI',
  },
  // --- locul pasului in tick (§2, B4)
  {
    n: 't.2b §2, B4 F5: pasul inainte de sincronizare (caldura in componenta de dinainte de lot)',
    f: 'src/sim/world.ts',
    a: '  sincronizeazaLumea(w, rules)\n  // Pasul de 1 Hz',
    b: '  if (w.tick % rules.ticksPerSecond === 0) pasTermic(w, rules)\n  sincronizeazaLumea(w, rules)\n  // Pasul de 1 Hz',
    e2: [{ f: 'src/sim/world.ts', a: '  if (w.tick % rules.ticksPerSecond === 0) pasTermic(w, rules)\n  w.tick++', b: '  w.tick++' }],
    t: TP, e: 'PAS oamenii dupa lot',
  },
  {
    n: 't.2b §1, B1: faza pasului alta decat w.tick % tps === 0',
    f: 'src/sim/world.ts',
    a: '  if (w.tick % rules.ticksPerSecond === 0) pasTermic(w, rules)',
    b: '  if (w.tick % rules.ticksPerSecond === 1) pasTermic(w, rules)',
    t: TP, e: 'PAS avansul termic',
  },
  // --- pasul (§5)
  {
    n: 't.2b §5.4, B4: prima linie a pasului lipseste (scenariul standard citeste rezervoarele)',
    f: F,
    a: '  if (w.camere.comp.size === 0) return null\n',
    b: '',
    t: TP, e: 'PAS scenariul standard',
  },
  {
    n: 't.2b §5.3: pasul refuzat de graf nu se reface (urgenta) si nu continua',
    f: F,
    a: '    r = pasPeGraf(w, go.value, rules, o)\n',
    b: '    return null\n',
    t: TS, e: 'STARE pasul nu arunca din tick',
  },
  {
    n: 't.2b §6: simetria muchiei nu se verifica la citire (pasul integreaza pe un graf stricat)',
    f: F,
    a: '      if (inv !== G) return refuse(',
    b: '      if (false) return refuse(',
    t: TS, e: 'STARE pasul nu arunca din tick',
  },
  {
    n: 't.2b §5: modelul pasului memorat fara stampila (dupa un lot, pasul integreaza pe graful vechi)',
    f: F,
    a: '  if (m !== undefined && m.reguli === rules && m.vazute === s.vazute && m.epoca === s.epoca && m.epocaFete === s.epocaFete) return m',
    b: '  if (m !== undefined) return m',
    t: TP, e: 'PAS T*',
  },
  {
    n: 't.2b §5.1, B4: oamenii nu se citesc (W 0)',
    f: F,
    a: '    W[k] = W[k]! + rules.termic.omW',
    b: '    W[k] = W[k]! + 0',
    t: TP, e: 'PAS oamenii pe hartie',
  },
  {
    n: 't.2b §5.1, B4: caldura rotunjita pe pion, nu o conversie pe nod',
    f: F,
    a: '      P = caldura(W[i]!, conv)',
    b: '      P = caldura(rules.termic.omW, conv) * (W[i]! / rules.termic.omW)',
    t: TP, e: 'PAS oamenii pe hartie',
  },
  {
    n: 't.2b §5.2, NUM-7: rezervoarele fata de T VECHI, nu fata de T* (dupa muchii si oameni)',
    f: F,
    a: '      for (let k = m.rStart[i]!; k < m.rStart[i + 1]!; k++) X += m.rG[k]! * (tRez[m.rBin[k]!]! - tStar)',
    b: '      for (let k = m.rStart[i]!; k < m.rStart[i + 1]!; k++) X += m.rG[k]! * (tRez[m.rBin[k]!]! - T[i]!)',
    t: TP, e: 'PAS T*',
  },
  {
    n: 't.2b §5.2, SAV-3: fluxul muchiei rotunjit cu floor (orientarea, deci eticheta, scapa in H)',
    f: F,
    a: '  if ((x < 0 ? -x : x) < prag) return rsN(x, 65536)',
    b: '  if ((x < 0 ? -x : x) < prag) return Math.floor(x / 65536)',
    t: TP, e: 'PAS orientarea',
  },
  {
    n: 't.2b §5.3, B1: marginea statica S·M (fara |T*|): o casa fierbinte ramane pe Number, X rotunjit tacut',
    f: F,
    a: '    if (S * (M + aT) < prag && (C + S) * 65536 < prag) {',
    b: '    if (S * M < prag && (C + S) * 65536 < prag) {',
    t: TP, e: 'PAS marginea dinamica',
  },
  {
    n: 't.2b §5.3, NUM-5: comutatorul nu trece si muchiile pe BigInt (pragul fix 2^52 pe muchie)',
    f: F,
    a: '  if ((x < 0 ? -x : x) < prag) return rsN(x, 65536)',
    b: '  if ((x < 0 ? -x : x) < PRAG_NUMBER) return rsN(x, 65536)',
    t: TP, e: 'PAS Number == BigInt',
  },
  {
    n: 't.2b §5.3: un T in afara intregilor siguri nu refuza pasul (o stare stricata se scrie, taiata de plasa, in loc sa fie refuzata)',
    f: F,
    a: '    if (!Number.isSafeInteger(T[i]!) || !Number.isSafeInteger(rest[i]!)) return refuse(',
    b: '    if (false) return refuse(',
    t: TP, e: 'PAS T in afara intregilor siguri',
  },
  // --- verdictul lotului si plasele de la rulare (GRAF-1, PAS-4)
  {
    n: 't.2b GRAF-1: refacerea de urgenta a grafului la lot nu se vede (delta stricata reparata tacut)',
    f: F,
    a: '  const deUrgenta = numarRefaceriDeUrgenta(w.camere) !== urgente',
    b: '  const deUrgenta = false',
    t: TS, e: 'STARE refacerea de urgenta a grafului la lot',
  },
  {
    n: 't.2b GRAF-1, SAV-R2: diferenta grafului la salvare nu se numara ca invariant (monitorul ecranului n-o vede)',
    f: F,
    a: '    invariant(st, refuse(Reason.INVARIANT_INCALCAT, { motiv: MOTIV_GRAF_LA_SALVARE, linie: cmp.params.linie }))',
    b: '    void 0',
    t: TSV, e: 'SALVARE compararea cu graful integral la encode',
  },
  {
    n: 't.2b PAS-4: verdictul lotului ignora abaterile evidentei maselor',
    f: F,
    a: '  if (l.abateri > 0) return refuse(',
    b: '  if (false) return refuse(',
    t: TS, e: 'STARE verdictul lotului',
  },
  {
    n: 't.2b PAS-4, GRAF-1: verdictul lotului ignora refacerea de urgenta',
    f: F,
    a: '  if (l.deUrgenta) return refuse(',
    b: '  if (false) return refuse(',
    t: TS, e: 'STARE verdictul lotului',
  },
  {
    n: 't.2b PAS-4: sursele provenientei fara T nu ajung la verdict',
    f: F,
    a: '    surseFaraT = p.surseFaraT',
    b: '    surseFaraT = 0',
    t: TS, e: 'STARE sursa fara T',
  },
  {
    n: 't.2b PAS-4: pasul nu verifica indexul fata de teren (pasul pe un index ramas in urma)',
    f: F,
    a: '  if (!stamp.ok || idx.teren !== w.terrain || idx.vazute !== w.terrain.editari) {',
    b: '  if (!stamp.ok) {',
    t: TS, e: 'STARE pas: indexul nu e la zi',
  },
  {
    n: 't.2b PAS-4: rezervoarele citite la pas nu se numara (scenariul standard le cere 0 — vid)',
    f: F,
    a: '  st.stat.rezervoareCitite++',
    b: '  void 0',
    t: TS, e: 'STARE rezervoareCitite',
  },
  // --- plasa de siguranta ±1000 °C (PROV-1 b)
  {
    n: 't.2b PROV-1 b: plasa nu taie dupa provenienta (pompa C3 duce T peste 1000 °C intre doi pasi, apoi peste marginea salvabila)',
    f: F,
    a: '    for (const y of sch.mase.noi) if (taieT(st.slot, y.id)) taiate++',
    b: '    for (const y of sch.mase.noi.slice(0, 0)) if (taieT(st.slot, y.id)) taiate++',
    t: TS, e: 'STARE plasa de siguranta',
  },
  {
    n: 't.2b PROV-1 b: plasa nu taie dupa pas (un content instabil diverge pana la intregii nesiguri)',
    f: F,
    a: '    if (taieT(sl, m.comp[i]!)) taieri++',
    b: '    if (false) taieri++',
    t: TP, e: 'PAS garda 6·g_max',
  },
  {
    n: 't.2b PROV-1 b: plasa taie doar in sus (−1000 °C nu e o margine)',
    f: F,
    a: '  else if (t < -T_SIGURANTA) sl.t[id] = -T_SIGURANTA',
    b: '  else if (false) sl.t[id] = -T_SIGURANTA',
    t: TP, e: 'PAS garda 6·g_max',
  },
  {
    n: 't.2b PROV-1 b: taierea dupa provenienta nu se numara ca invariant (nicio alerta)',
    f: F,
    a: '    invariant(st, t)\n    if (o.ok) o = t',
    b: '    if (o.ok) o = t',
    t: TS, e: 'STARE plasa de siguranta',
  },
  // --- commit-ul 5: salvarea (§7, §9)
  {
    n: 't.2b §9 a, B1: restul nescris in salvare (lumea incarcata porneste cu rest 0)',
    f: F,
    a: '    b.rest.push(r)',
    b: '    b.rest.push(0)',
    t: TSV, e: 'SALVARE M5-faze pe S+',
  },
  {
    n: 't.2b §9 a, B1: faza de la incarcare (lumea incarcata paseste in clipa incarcarii)',
    f: 'src/sim/save.ts',
    a: '  const construit = valideazaJoburiDeConstruit(w, rules)',
    b: '  pasTermic(w, rules)\n  const construit = valideazaJoburiDeConstruit(w, rules)',
    e2: [{ f: 'src/sim/save.ts', a: "import { blocTemperaturi, incarcaTemperaturi, temperaturaLaEchilibru, temperaturaLaZi } from './temperatura.ts'", b: "import { blocTemperaturi, incarcaTemperaturi, pasTermic, temperaturaLaEchilibru, temperaturaLaZi } from './temperatura.ts'" }],
    t: TSV, e: 'SALVARE M5-faze pe S+',
  },
  {
    n: 't.2b §9 a, B1/SAV: cheia pe SLOT — T si restul scrise in ordinea sloturilor, langa ancorele in ordinea lor',
    f: F,
    a: '    const t = sl.t[c.id]!\n    const r = sl.rest[c.id]!',
    b: '    const s0 = [...w.camere.comp.keys()].sort((p, q) => p - q)[i]!\n    const t = sl.t[s0]!\n    const r = sl.rest[s0]!',
    t: TSV, e: 'SALVARE M5-faze pe S+',
  },
  {
    n: 't.2b §9 b, verif-IDX-2: C3 neaplicat pe loturile doar-fete (fill pe apa: masa se schimba, T nu stie)',
    f: F,
    a: '  if (sch.mase.noi.length > 0 || sch.moarte.length > 0) {',
    b: '  if (sch.felii.length > 0 || sch.recalcul) {',
    t: 'tests/provenienta.test.ts', e: 'PROVENIENTA prin COMENZI, lot DOAR-FETE',
  },
  {
    n: 't.2b §9 b, verif-SAV-1: graful refacut doar la epoca (lotul doar-fete lasa graful vechi sub stampila noua)',
    f: 'src/sim/termic.ts',
    a: '  if (sch.bucatiMoarte.length > 0 || sch.bucatiNascute.length > 0 || sch.bucatiRescrise.length > 0 || sch.noi.length > 0) {',
    b: '  if (sch.felii.length > 0 && (sch.bucatiMoarte.length > 0 || sch.bucatiNascute.length > 0 || sch.noi.length > 0)) {',
    t: TSV, e: 'SALVARE M5-fete',
  },
  {
    n: 't.2b §6, IDX-4: salvarea nu compara graful incremental cu cel integral (o delta gresita fara asimetrie trece)',
    f: F,
    a: '  const cmp = comparaGrafulCuIntegral(w.camere, rules)',
    b: '  const cmp = accept(null)',
    t: TSV, e: 'SALVARE compararea cu graful integral la encode',
  },
  {
    n: 't.2b §7, SAV-2: validarea stricta fara amprenta (o salvare cu alt content se refuza)',
    f: F,
    a: '  const strict = amprentaCapacitatii(cap) === b.amprenta',
    b: '  const strict = true',
    t: TSV, e: 'SALVARE M5-content',
  },
  {
    n: 't.2b §7, SAV-2: amprenta ignorata (rest ≥ C\' cu aceeasi amprenta se normalizeaza in loc sa se refuze)',
    f: F,
    a: '  const strict = amprentaCapacitatii(cap) === b.amprenta',
    b: '  const strict = false',
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, B1: ancorele nu se cer strict crescatoare (o ancora duplicata lasa o componenta fara T)',
    f: F,
    a: '(i > 0 && a <= (anc[i - 1] as number))',
    b: '(i > 0 && false)',
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, B1: o ancora fara componenta nu se refuza',
    f: F,
    a: '    if (c === undefined) return refuse(Reason.ENTITATE_INEXISTENTA,',
    b: '    if (false) return refuse(Reason.ENTITATE_INEXISTENTA,',
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, B1: numarul de intrari nu se compara cu al componentelor (o intrare lipsa lasa o componenta fara T)',
    f: F,
    a: '  if (anc.length !== camere.comp.size) return refuse(',
    b: '  if (false) return refuse(',
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, SAV-4: T peste 2^31 acceptat la decode (hash-ul il scrie ca i32: doua stari, acelasi hash)',
    f: F,
    a: "|| t < T_MIN || t >= T_LIMITA) return refuse(Reason.VALOARE_INVALIDA, { camp: 'temperaturi.t', ancora: a,",
    b: ") return refuse(Reason.VALOARE_INVALIDA, { camp: 'temperaturi.t', ancora: a,",
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, SAV-4: T fractionar acceptat la decode',
    f: F,
    a: "typeof t !== 'number' || !Number.isSafeInteger(t) || t < T_MIN",
    b: "typeof t !== 'number' || t < T_MIN",
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, SAV-4: rest negativ acceptat la decode',
    f: F,
    a: "typeof r !== 'number' || !Number.isSafeInteger(r) || r < 0) return refuse(",
    b: "typeof r !== 'number' || !Number.isSafeInteger(r)) return refuse(",
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7: amprenta lipsa sau invalida acceptata (lumea se normalizeaza tacut)',
    f: F,
    a: "  if (typeof b.amprenta !== 'number' || !Number.isInteger(b.amprenta)",
    b: "  if (false && (typeof b.amprenta !== 'number') || !Number.isInteger(0)",
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, B1: bloc de temperatura acceptat intr-o salvare de schema < 8',
    f: 'src/sim/save.ts',
    a: '  if (env.schema < 8 && data.temperaturi !== undefined) return refuse(',
    b: '  if (false) return refuse(',
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, B1: blocul lipsa intr-o salvare de schema 8 acceptat (componentele raman fara T)',
    f: 'src/sim/save.ts',
    a: '  if (env.schema >= 8 && data.temperaturi === undefined) return refuse(',
    b: '  if (false) return refuse(',
    t: TSV, e: 'SALVARE refuzurile blocului',
  },
  {
    n: 't.2b §7, SAV-4: encode scrie un T in afara lui [−2^31, 2^31)',
    f: F,
    a: '    if (!Number.isSafeInteger(t) || t < T_MIN || t >= T_LIMITA) return refuse(',
    b: '    if (false) return refuse(',
    t: TSV, e: 'SALVARE encode arunca',
  },
  {
    n: 't.2b §7, SAV-4: encode scrie un rest ≥ C\' sau negativ',
    f: F,
    a: '    if (!Number.isSafeInteger(r) || r < 0 || r >= cap[i]!) return refuse(',
    b: '    if (false) return refuse(',
    t: TSV, e: 'SALVARE encode arunca',
  },
  {
    n: 't.2b §7, B1: MIGRATIONS[7] lipseste (orice salvare veche se refuza)',
    f: 'src/sim/save.ts',
    a: '  7: (d) => d,',
    b: '',
    t: 'tests/migrare-incaperi.test.ts', e: 'toate cele 7 fixturi golden',
  },
  {
    n: 't.2b §7: T nu intra in hash',
    f: 'src/sim/hash.ts',
    a: '    h.i32(temp.t[c.id] ?? 0)',
    b: '    h.i32(0)',
    t: TSV, e: 'SALVARE scena S+',
  },
  {
    n: 't.2b §7: restul nu intra in hash',
    f: 'src/sim/hash.ts',
    a: '    h.u32(Math.floor(r / 4294967296)).u32(r % 4294967296)',
    b: '    h.u32(0).u32(0)',
    t: TSV, e: 'SALVARE scena S+',
  },
  {
    n: 't.2b §7, B1: hash-ul temperaturii in ordinea SLOTURILOR (doua lumi egale, cu alte id-uri, dau alt hash)',
    f: 'src/sim/hash.ts',
    a: '  const lista = listaComponente(w.camere)',
    b: '  const lista = [...w.camere.comp.values()]',
    t: TSV, e: 'SALVARE scena S+',
  },
  // --- acceptanțele (§9)
  {
    n: 't.2b §3, NUM-3/JOC-1: regula A — solul care intra nu poarta T_sol, ia T-ul rezultat (pivnita sapata din casa porneste calda)',
    f: F,
    a: '  h = adun(h, energiaSolului(y.solIntra, tick, rules, c), c)\n  W += masaSolului(y.solIntra, rules)',
    b: '',
    t: 'tests/pivnita-acceptanta.test.ts', e: 'PIVNITA acceptanta relativa',
  },
  {
    n: 't.2b §10 d.3, verif-JOC-3: unirea ia T-ul unei singure surse, nu media pe masa',
    f: F,
    a: '  for (const s of y.surse) {',
    b: '  for (const s of y.surse.slice(0, 1)) {',
    t: 'tests/pivnita-acceptanta.test.ts', e: 'PIVNITA usa scoasa si pusa la loc',
  },
  {
    n: 't.2b §9, B4: puterea omului triplata (dormitorul +0,7 °C, peste banda)',
    f: F,
    a: '    W[k] = W[k]! + rules.termic.omW',
    b: '    W[k] = W[k]! + 3 * rules.termic.omW',
    t: 'tests/oameni-casa.test.ts', e: 'OAMENII pe ocuparea reala',
  },
]
